/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AddChannelLogBodySchema} from './model/AddChannelLogBodySchema';
import {AnyOfClaimSchemaType} from './model/AnyOfClaimSchemaType';
import {AnyOfDeviceSchemaAddressImage} from './model/AnyOfDeviceSchemaAddressImage';
import {AnyOfDeviceSchemaAddressSameAs} from './model/AnyOfDeviceSchemaAddressSameAs';
import {AnyOfDeviceSchemaConfiguration} from './model/AnyOfDeviceSchemaConfiguration';
import {AnyOfDeviceSchemaControlledAsset} from './model/AnyOfDeviceSchemaControlledAsset';
import {AnyOfDeviceSchemaControlledPropertyItems} from './model/AnyOfDeviceSchemaControlledPropertyItems';
import {AnyOfDeviceSchemaDataProvider} from './model/AnyOfDeviceSchemaDataProvider';
import {AnyOfDeviceSchemaImage} from './model/AnyOfDeviceSchemaImage';
import {AnyOfDeviceSchemaOwner} from './model/AnyOfDeviceSchemaOwner';
import {AnyOfDeviceSchemaProvider} from './model/AnyOfDeviceSchemaProvider';
import {AnyOfDeviceSchemaRssi} from './model/AnyOfDeviceSchemaRssi';
import {AnyOfDeviceSchemaSameAs} from './model/AnyOfDeviceSchemaSameAs';
import {AnyOfDeviceSchemaSource} from './model/AnyOfDeviceSchemaSource';
import {AnyOfDeviceSchemaValue} from './model/AnyOfDeviceSchemaValue';
import {AnyOfOrganizationSchemaAddress} from './model/AnyOfOrganizationSchemaAddress';
import {AnyOfOrganizationSchemaBrand} from './model/AnyOfOrganizationSchemaBrand';
import {AnyOfOrganizationSchemaImage} from './model/AnyOfOrganizationSchemaImage';
import {AnyOfOrganizationSchemaSameAs} from './model/AnyOfOrganizationSchemaSameAs';
import {AnyOfPersonSchemaAddress} from './model/AnyOfPersonSchemaAddress';
import {AnyOfPersonSchemaColleague} from './model/AnyOfPersonSchemaColleague';
import {AnyOfPersonSchemaHeight} from './model/AnyOfPersonSchemaHeight';
import {AnyOfPersonSchemaImage} from './model/AnyOfPersonSchemaImage';
import {AnyOfPersonSchemaMemberOf} from './model/AnyOfPersonSchemaMemberOf';
import {AnyOfPersonSchemaSameAs} from './model/AnyOfPersonSchemaSameAs';
import {AnyOfPersonSchemaWeight} from './model/AnyOfPersonSchemaWeight';
import {AnyOfPersonSchemaWorksFor} from './model/AnyOfPersonSchemaWorksFor';
import {AnyOfProductSchemaAggregateRatingAuthorImage} from './model/AnyOfProductSchemaAggregateRatingAuthorImage';
import {AnyOfProductSchemaAggregateRatingAuthorSameAs} from './model/AnyOfProductSchemaAggregateRatingAuthorSameAs';
import {AnyOfProductSchemaAggregateRatingBestRating} from './model/AnyOfProductSchemaAggregateRatingBestRating';
import {AnyOfProductSchemaAggregateRatingImage} from './model/AnyOfProductSchemaAggregateRatingImage';
import {AnyOfProductSchemaAggregateRatingRatingValue} from './model/AnyOfProductSchemaAggregateRatingRatingValue';
import {AnyOfProductSchemaAggregateRatingReviewCount} from './model/AnyOfProductSchemaAggregateRatingReviewCount';
import {AnyOfProductSchemaAggregateRatingSameAs} from './model/AnyOfProductSchemaAggregateRatingSameAs';
import {AnyOfProductSchemaAggregateRatingWorstRating} from './model/AnyOfProductSchemaAggregateRatingWorstRating';
import {AnyOfProductSchemaBrand} from './model/AnyOfProductSchemaBrand';
import {AnyOfProductSchemaHeight} from './model/AnyOfProductSchemaHeight';
import {AnyOfProductSchemaImage} from './model/AnyOfProductSchemaImage';
import {AnyOfProductSchemaManufacturerAddress} from './model/AnyOfProductSchemaManufacturerAddress';
import {AnyOfProductSchemaManufacturerBrand} from './model/AnyOfProductSchemaManufacturerBrand';
import {AnyOfProductSchemaManufacturerImage} from './model/AnyOfProductSchemaManufacturerImage';
import {AnyOfProductSchemaManufacturerSameAs} from './model/AnyOfProductSchemaManufacturerSameAs';
import {AnyOfProductSchemaMaterial} from './model/AnyOfProductSchemaMaterial';
import {AnyOfProductSchemaOffers} from './model/AnyOfProductSchemaOffers';
import {AnyOfProductSchemaReviewImage} from './model/AnyOfProductSchemaReviewImage';
import {AnyOfProductSchemaReviewReviewRatingBestRating} from './model/AnyOfProductSchemaReviewReviewRatingBestRating';
import {AnyOfProductSchemaReviewReviewRatingImage} from './model/AnyOfProductSchemaReviewReviewRatingImage';
import {AnyOfProductSchemaReviewReviewRatingRatingValue} from './model/AnyOfProductSchemaReviewReviewRatingRatingValue';
import {AnyOfProductSchemaReviewReviewRatingSameAs} from './model/AnyOfProductSchemaReviewReviewRatingSameAs';
import {AnyOfProductSchemaReviewReviewRatingWorstRating} from './model/AnyOfProductSchemaReviewReviewRatingWorstRating';
import {AnyOfProductSchemaReviewSameAs} from './model/AnyOfProductSchemaReviewSameAs';
import {AnyOfProductSchemaSameAs} from './model/AnyOfProductSchemaSameAs';
import {AnyOfProductSchemaSize} from './model/AnyOfProductSchemaSize';
import {AnyOfProductSchemaWeight} from './model/AnyOfProductSchemaWeight';
import {AnyOfProductSchemaWidth} from './model/AnyOfProductSchemaWidth';
import {AnyOfServiceSchemaAvailableChannelImage} from './model/AnyOfServiceSchemaAvailableChannelImage';
import {AnyOfServiceSchemaAvailableChannelSameAs} from './model/AnyOfServiceSchemaAvailableChannelSameAs';
import {AnyOfServiceSchemaBrand} from './model/AnyOfServiceSchemaBrand';
import {AnyOfServiceSchemaImage} from './model/AnyOfServiceSchemaImage';
import {AnyOfServiceSchemaOffers} from './model/AnyOfServiceSchemaOffers';
import {AnyOfServiceSchemaProvider} from './model/AnyOfServiceSchemaProvider';
import {AnyOfServiceSchemaReview} from './model/AnyOfServiceSchemaReview';
import {AnyOfServiceSchemaSameAs} from './model/AnyOfServiceSchemaSameAs';
import {AnyOfServiceSchemaServiceOutput} from './model/AnyOfServiceSchemaServiceOutput';
import {AnyOfVerifyIdentityBodySchemaSubjectClaimType} from './model/AnyOfVerifyIdentityBodySchemaSubjectClaimType';
import {AuthorizeSubscriptionBodySchema} from './model/AuthorizeSubscriptionBodySchema';
import {AuthorizeSubscriptionResponseSchema} from './model/AuthorizeSubscriptionResponseSchema';
import {ChannelAddressSchema} from './model/ChannelAddressSchema';
import {ChannelDataSchema} from './model/ChannelDataSchema';
import {ChannelDataSchemaLog} from './model/ChannelDataSchemaLog';
import {ChannelInfoSchema} from './model/ChannelInfoSchema';
import {ChannelInfoSearchSchema} from './model/ChannelInfoSearchSchema';
import {ClaimSchema} from './model/ClaimSchema';
import {CreateChannelBodySchema} from './model/CreateChannelBodySchema';
import {CreateChannelBodySchemaTopics} from './model/CreateChannelBodySchemaTopics';
import {CreateChannelResponseSchema} from './model/CreateChannelResponseSchema';
import {CreateIdentityBodySchema} from './model/CreateIdentityBodySchema';
import {DeviceSchema} from './model/DeviceSchema';
import {DeviceSchemaAddress} from './model/DeviceSchemaAddress';
import {DocumentJsonUpdateSchema} from './model/DocumentJsonUpdateSchema';
import {ErrorResponseSchema} from './model/ErrorResponseSchema';
import {IdentityDocumentJsonSchema} from './model/IdentityDocumentJsonSchema';
import {IdentityIdSchema} from './model/IdentityIdSchema';
import {IdentityJsonSchema} from './model/IdentityJsonSchema';
import {IdentityJsonSchemaDoc} from './model/IdentityJsonSchemaDoc';
import {IdentityJsonSchemaDocProof} from './model/IdentityJsonSchemaDocProof';
import {IdentityJsonSchemaDocVerificationMethod} from './model/IdentityJsonSchemaDocVerificationMethod';
import {IdentityJsonSchemaKey} from './model/IdentityJsonSchemaKey';
import {IdentityJsonUpdateSchema} from './model/IdentityJsonUpdateSchema';
import {IdentityKeyPairJsonSchema} from './model/IdentityKeyPairJsonSchema';
import {IdentitySchema} from './model/IdentitySchema';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse401} from './model/InlineResponse401';
import {LatestIdentityJsonSchema} from './model/LatestIdentityJsonSchema';
import {NonceSchema} from './model/NonceSchema';
import {OrganizationSchema} from './model/OrganizationSchema';
import {PersonSchema} from './model/PersonSchema';
import {ProductSchema} from './model/ProductSchema';
import {ProductSchemaAggregateRating} from './model/ProductSchemaAggregateRating';
import {ProductSchemaAggregateRatingAuthor} from './model/ProductSchemaAggregateRatingAuthor';
import {ProductSchemaManufacturer} from './model/ProductSchemaManufacturer';
import {ProductSchemaReview} from './model/ProductSchemaReview';
import {ProductSchemaReviewReviewRating} from './model/ProductSchemaReviewReviewRating';
import {ProveOwnershipPostBodySchema} from './model/ProveOwnershipPostBodySchema';
import {ReimportBodySchema} from './model/ReimportBodySchema';
import {RequestSubscriptionBodySchema} from './model/RequestSubscriptionBodySchema';
import {RequestSubscriptionResponseSchema} from './model/RequestSubscriptionResponseSchema';
import {RevokeSubscriptionBodySchema} from './model/RevokeSubscriptionBodySchema';
import {RevokeVerificationBodySchema} from './model/RevokeVerificationBodySchema';
import {ServiceSchema} from './model/ServiceSchema';
import {ServiceSchemaAvailableChannel} from './model/ServiceSchemaAvailableChannel';
import {SubjectBodySchema} from './model/SubjectBodySchema';
import {SubscriptionSchema} from './model/SubscriptionSchema';
import {SubscriptionUpdateSchema} from './model/SubscriptionUpdateSchema';
import {TopicSchema} from './model/TopicSchema';
import {TrustedRootBodySchema} from './model/TrustedRootBodySchema';
import {UpdateIdentityBodySchema} from './model/UpdateIdentityBodySchema';
import {ValidateBodySchema} from './model/ValidateBodySchema';
import {ValidateBodySchemaInner} from './model/ValidateBodySchemaInner';
import {ValidateResponseSchema} from './model/ValidateResponseSchema';
import {ValidateResponseSchemaInner} from './model/ValidateResponseSchemaInner';
import {VerifiableCredentialBodySchema} from './model/VerifiableCredentialBodySchema';
import {VerifiableCredentialSchema} from './model/VerifiableCredentialSchema';
import {VerifiableCredentialSubjectSchema} from './model/VerifiableCredentialSubjectSchema';
import {VerifyIdentityBodySchema} from './model/VerifyIdentityBodySchema';
import {VerifyIdentityBodySchemaInitiatorVC} from './model/VerifyIdentityBodySchemaInitiatorVC';
import {VerifyIdentityBodySchemaInitiatorVCCredentialSubject} from './model/VerifyIdentityBodySchemaInitiatorVCCredentialSubject';
import {VerifyIdentityBodySchemaInitiatorVCProof} from './model/VerifyIdentityBodySchemaInitiatorVCProof';
import {VerifyIdentityBodySchemaSubject} from './model/VerifyIdentityBodySchemaSubject';
import {VerifyIdentityBodySchemaSubjectClaim} from './model/VerifyIdentityBodySchemaSubjectClaim';
import {AuthenticationApi} from './api/AuthenticationApi';
import {ChannelInfoApi} from './api/ChannelInfoApi';
import {ChannelsApi} from './api/ChannelsApi';
import {IdentitiesApi} from './api/IdentitiesApi';
import {ServerInfoApi} from './api/ServerInfoApi';
import {SubscriptionsApi} from './api/SubscriptionsApi';
import {VerificationApi} from './api/VerificationApi';

/**
* This_is_the_API_documentation_for_the_Integration_Services__Have_a_look_at_the_repository_for_examples_at__Github_httpsgithub_comiotaledgerintegration_services_____________For_further_information_on_the_Audit_Trail_GW_API_have_a_look_at__Audit_Trail_API_httpsgithub_comiotaledgerintegration_servicesblobmasterapiusage_audit_trail_GW_md_and_head_to_____________SSI_Bridge_httpsgithub_comiotaledgerintegration_servicesblobmasterapiusage_ssi_bridge_md_for_information_about_the_SSI_Bridge_____________.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var IntegrationServicesApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new IntegrationServicesApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new IntegrationServicesApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new IntegrationServicesApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new IntegrationServicesApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddChannelLogBodySchema model constructor.
     * @property {module:model/AddChannelLogBodySchema}
     */
    AddChannelLogBodySchema,

    /**
     * The AnyOfClaimSchemaType model constructor.
     * @property {module:model/AnyOfClaimSchemaType}
     */
    AnyOfClaimSchemaType,

    /**
     * The AnyOfDeviceSchemaAddressImage model constructor.
     * @property {module:model/AnyOfDeviceSchemaAddressImage}
     */
    AnyOfDeviceSchemaAddressImage,

    /**
     * The AnyOfDeviceSchemaAddressSameAs model constructor.
     * @property {module:model/AnyOfDeviceSchemaAddressSameAs}
     */
    AnyOfDeviceSchemaAddressSameAs,

    /**
     * The AnyOfDeviceSchemaConfiguration model constructor.
     * @property {module:model/AnyOfDeviceSchemaConfiguration}
     */
    AnyOfDeviceSchemaConfiguration,

    /**
     * The AnyOfDeviceSchemaControlledAsset model constructor.
     * @property {module:model/AnyOfDeviceSchemaControlledAsset}
     */
    AnyOfDeviceSchemaControlledAsset,

    /**
     * The AnyOfDeviceSchemaControlledPropertyItems model constructor.
     * @property {module:model/AnyOfDeviceSchemaControlledPropertyItems}
     */
    AnyOfDeviceSchemaControlledPropertyItems,

    /**
     * The AnyOfDeviceSchemaDataProvider model constructor.
     * @property {module:model/AnyOfDeviceSchemaDataProvider}
     */
    AnyOfDeviceSchemaDataProvider,

    /**
     * The AnyOfDeviceSchemaImage model constructor.
     * @property {module:model/AnyOfDeviceSchemaImage}
     */
    AnyOfDeviceSchemaImage,

    /**
     * The AnyOfDeviceSchemaOwner model constructor.
     * @property {module:model/AnyOfDeviceSchemaOwner}
     */
    AnyOfDeviceSchemaOwner,

    /**
     * The AnyOfDeviceSchemaProvider model constructor.
     * @property {module:model/AnyOfDeviceSchemaProvider}
     */
    AnyOfDeviceSchemaProvider,

    /**
     * The AnyOfDeviceSchemaRssi model constructor.
     * @property {module:model/AnyOfDeviceSchemaRssi}
     */
    AnyOfDeviceSchemaRssi,

    /**
     * The AnyOfDeviceSchemaSameAs model constructor.
     * @property {module:model/AnyOfDeviceSchemaSameAs}
     */
    AnyOfDeviceSchemaSameAs,

    /**
     * The AnyOfDeviceSchemaSource model constructor.
     * @property {module:model/AnyOfDeviceSchemaSource}
     */
    AnyOfDeviceSchemaSource,

    /**
     * The AnyOfDeviceSchemaValue model constructor.
     * @property {module:model/AnyOfDeviceSchemaValue}
     */
    AnyOfDeviceSchemaValue,

    /**
     * The AnyOfOrganizationSchemaAddress model constructor.
     * @property {module:model/AnyOfOrganizationSchemaAddress}
     */
    AnyOfOrganizationSchemaAddress,

    /**
     * The AnyOfOrganizationSchemaBrand model constructor.
     * @property {module:model/AnyOfOrganizationSchemaBrand}
     */
    AnyOfOrganizationSchemaBrand,

    /**
     * The AnyOfOrganizationSchemaImage model constructor.
     * @property {module:model/AnyOfOrganizationSchemaImage}
     */
    AnyOfOrganizationSchemaImage,

    /**
     * The AnyOfOrganizationSchemaSameAs model constructor.
     * @property {module:model/AnyOfOrganizationSchemaSameAs}
     */
    AnyOfOrganizationSchemaSameAs,

    /**
     * The AnyOfPersonSchemaAddress model constructor.
     * @property {module:model/AnyOfPersonSchemaAddress}
     */
    AnyOfPersonSchemaAddress,

    /**
     * The AnyOfPersonSchemaColleague model constructor.
     * @property {module:model/AnyOfPersonSchemaColleague}
     */
    AnyOfPersonSchemaColleague,

    /**
     * The AnyOfPersonSchemaHeight model constructor.
     * @property {module:model/AnyOfPersonSchemaHeight}
     */
    AnyOfPersonSchemaHeight,

    /**
     * The AnyOfPersonSchemaImage model constructor.
     * @property {module:model/AnyOfPersonSchemaImage}
     */
    AnyOfPersonSchemaImage,

    /**
     * The AnyOfPersonSchemaMemberOf model constructor.
     * @property {module:model/AnyOfPersonSchemaMemberOf}
     */
    AnyOfPersonSchemaMemberOf,

    /**
     * The AnyOfPersonSchemaSameAs model constructor.
     * @property {module:model/AnyOfPersonSchemaSameAs}
     */
    AnyOfPersonSchemaSameAs,

    /**
     * The AnyOfPersonSchemaWeight model constructor.
     * @property {module:model/AnyOfPersonSchemaWeight}
     */
    AnyOfPersonSchemaWeight,

    /**
     * The AnyOfPersonSchemaWorksFor model constructor.
     * @property {module:model/AnyOfPersonSchemaWorksFor}
     */
    AnyOfPersonSchemaWorksFor,

    /**
     * The AnyOfProductSchemaAggregateRatingAuthorImage model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingAuthorImage}
     */
    AnyOfProductSchemaAggregateRatingAuthorImage,

    /**
     * The AnyOfProductSchemaAggregateRatingAuthorSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingAuthorSameAs}
     */
    AnyOfProductSchemaAggregateRatingAuthorSameAs,

    /**
     * The AnyOfProductSchemaAggregateRatingBestRating model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingBestRating}
     */
    AnyOfProductSchemaAggregateRatingBestRating,

    /**
     * The AnyOfProductSchemaAggregateRatingImage model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingImage}
     */
    AnyOfProductSchemaAggregateRatingImage,

    /**
     * The AnyOfProductSchemaAggregateRatingRatingValue model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingRatingValue}
     */
    AnyOfProductSchemaAggregateRatingRatingValue,

    /**
     * The AnyOfProductSchemaAggregateRatingReviewCount model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingReviewCount}
     */
    AnyOfProductSchemaAggregateRatingReviewCount,

    /**
     * The AnyOfProductSchemaAggregateRatingSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingSameAs}
     */
    AnyOfProductSchemaAggregateRatingSameAs,

    /**
     * The AnyOfProductSchemaAggregateRatingWorstRating model constructor.
     * @property {module:model/AnyOfProductSchemaAggregateRatingWorstRating}
     */
    AnyOfProductSchemaAggregateRatingWorstRating,

    /**
     * The AnyOfProductSchemaBrand model constructor.
     * @property {module:model/AnyOfProductSchemaBrand}
     */
    AnyOfProductSchemaBrand,

    /**
     * The AnyOfProductSchemaHeight model constructor.
     * @property {module:model/AnyOfProductSchemaHeight}
     */
    AnyOfProductSchemaHeight,

    /**
     * The AnyOfProductSchemaImage model constructor.
     * @property {module:model/AnyOfProductSchemaImage}
     */
    AnyOfProductSchemaImage,

    /**
     * The AnyOfProductSchemaManufacturerAddress model constructor.
     * @property {module:model/AnyOfProductSchemaManufacturerAddress}
     */
    AnyOfProductSchemaManufacturerAddress,

    /**
     * The AnyOfProductSchemaManufacturerBrand model constructor.
     * @property {module:model/AnyOfProductSchemaManufacturerBrand}
     */
    AnyOfProductSchemaManufacturerBrand,

    /**
     * The AnyOfProductSchemaManufacturerImage model constructor.
     * @property {module:model/AnyOfProductSchemaManufacturerImage}
     */
    AnyOfProductSchemaManufacturerImage,

    /**
     * The AnyOfProductSchemaManufacturerSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaManufacturerSameAs}
     */
    AnyOfProductSchemaManufacturerSameAs,

    /**
     * The AnyOfProductSchemaMaterial model constructor.
     * @property {module:model/AnyOfProductSchemaMaterial}
     */
    AnyOfProductSchemaMaterial,

    /**
     * The AnyOfProductSchemaOffers model constructor.
     * @property {module:model/AnyOfProductSchemaOffers}
     */
    AnyOfProductSchemaOffers,

    /**
     * The AnyOfProductSchemaReviewImage model constructor.
     * @property {module:model/AnyOfProductSchemaReviewImage}
     */
    AnyOfProductSchemaReviewImage,

    /**
     * The AnyOfProductSchemaReviewReviewRatingBestRating model constructor.
     * @property {module:model/AnyOfProductSchemaReviewReviewRatingBestRating}
     */
    AnyOfProductSchemaReviewReviewRatingBestRating,

    /**
     * The AnyOfProductSchemaReviewReviewRatingImage model constructor.
     * @property {module:model/AnyOfProductSchemaReviewReviewRatingImage}
     */
    AnyOfProductSchemaReviewReviewRatingImage,

    /**
     * The AnyOfProductSchemaReviewReviewRatingRatingValue model constructor.
     * @property {module:model/AnyOfProductSchemaReviewReviewRatingRatingValue}
     */
    AnyOfProductSchemaReviewReviewRatingRatingValue,

    /**
     * The AnyOfProductSchemaReviewReviewRatingSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaReviewReviewRatingSameAs}
     */
    AnyOfProductSchemaReviewReviewRatingSameAs,

    /**
     * The AnyOfProductSchemaReviewReviewRatingWorstRating model constructor.
     * @property {module:model/AnyOfProductSchemaReviewReviewRatingWorstRating}
     */
    AnyOfProductSchemaReviewReviewRatingWorstRating,

    /**
     * The AnyOfProductSchemaReviewSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaReviewSameAs}
     */
    AnyOfProductSchemaReviewSameAs,

    /**
     * The AnyOfProductSchemaSameAs model constructor.
     * @property {module:model/AnyOfProductSchemaSameAs}
     */
    AnyOfProductSchemaSameAs,

    /**
     * The AnyOfProductSchemaSize model constructor.
     * @property {module:model/AnyOfProductSchemaSize}
     */
    AnyOfProductSchemaSize,

    /**
     * The AnyOfProductSchemaWeight model constructor.
     * @property {module:model/AnyOfProductSchemaWeight}
     */
    AnyOfProductSchemaWeight,

    /**
     * The AnyOfProductSchemaWidth model constructor.
     * @property {module:model/AnyOfProductSchemaWidth}
     */
    AnyOfProductSchemaWidth,

    /**
     * The AnyOfServiceSchemaAvailableChannelImage model constructor.
     * @property {module:model/AnyOfServiceSchemaAvailableChannelImage}
     */
    AnyOfServiceSchemaAvailableChannelImage,

    /**
     * The AnyOfServiceSchemaAvailableChannelSameAs model constructor.
     * @property {module:model/AnyOfServiceSchemaAvailableChannelSameAs}
     */
    AnyOfServiceSchemaAvailableChannelSameAs,

    /**
     * The AnyOfServiceSchemaBrand model constructor.
     * @property {module:model/AnyOfServiceSchemaBrand}
     */
    AnyOfServiceSchemaBrand,

    /**
     * The AnyOfServiceSchemaImage model constructor.
     * @property {module:model/AnyOfServiceSchemaImage}
     */
    AnyOfServiceSchemaImage,

    /**
     * The AnyOfServiceSchemaOffers model constructor.
     * @property {module:model/AnyOfServiceSchemaOffers}
     */
    AnyOfServiceSchemaOffers,

    /**
     * The AnyOfServiceSchemaProvider model constructor.
     * @property {module:model/AnyOfServiceSchemaProvider}
     */
    AnyOfServiceSchemaProvider,

    /**
     * The AnyOfServiceSchemaReview model constructor.
     * @property {module:model/AnyOfServiceSchemaReview}
     */
    AnyOfServiceSchemaReview,

    /**
     * The AnyOfServiceSchemaSameAs model constructor.
     * @property {module:model/AnyOfServiceSchemaSameAs}
     */
    AnyOfServiceSchemaSameAs,

    /**
     * The AnyOfServiceSchemaServiceOutput model constructor.
     * @property {module:model/AnyOfServiceSchemaServiceOutput}
     */
    AnyOfServiceSchemaServiceOutput,

    /**
     * The AnyOfVerifyIdentityBodySchemaSubjectClaimType model constructor.
     * @property {module:model/AnyOfVerifyIdentityBodySchemaSubjectClaimType}
     */
    AnyOfVerifyIdentityBodySchemaSubjectClaimType,

    /**
     * The AuthorizeSubscriptionBodySchema model constructor.
     * @property {module:model/AuthorizeSubscriptionBodySchema}
     */
    AuthorizeSubscriptionBodySchema,

    /**
     * The AuthorizeSubscriptionResponseSchema model constructor.
     * @property {module:model/AuthorizeSubscriptionResponseSchema}
     */
    AuthorizeSubscriptionResponseSchema,

    /**
     * The ChannelAddressSchema model constructor.
     * @property {module:model/ChannelAddressSchema}
     */
    ChannelAddressSchema,

    /**
     * The ChannelDataSchema model constructor.
     * @property {module:model/ChannelDataSchema}
     */
    ChannelDataSchema,

    /**
     * The ChannelDataSchemaLog model constructor.
     * @property {module:model/ChannelDataSchemaLog}
     */
    ChannelDataSchemaLog,

    /**
     * The ChannelInfoSchema model constructor.
     * @property {module:model/ChannelInfoSchema}
     */
    ChannelInfoSchema,

    /**
     * The ChannelInfoSearchSchema model constructor.
     * @property {module:model/ChannelInfoSearchSchema}
     */
    ChannelInfoSearchSchema,

    /**
     * The ClaimSchema model constructor.
     * @property {module:model/ClaimSchema}
     */
    ClaimSchema,

    /**
     * The CreateChannelBodySchema model constructor.
     * @property {module:model/CreateChannelBodySchema}
     */
    CreateChannelBodySchema,

    /**
     * The CreateChannelBodySchemaTopics model constructor.
     * @property {module:model/CreateChannelBodySchemaTopics}
     */
    CreateChannelBodySchemaTopics,

    /**
     * The CreateChannelResponseSchema model constructor.
     * @property {module:model/CreateChannelResponseSchema}
     */
    CreateChannelResponseSchema,

    /**
     * The CreateIdentityBodySchema model constructor.
     * @property {module:model/CreateIdentityBodySchema}
     */
    CreateIdentityBodySchema,

    /**
     * The DeviceSchema model constructor.
     * @property {module:model/DeviceSchema}
     */
    DeviceSchema,

    /**
     * The DeviceSchemaAddress model constructor.
     * @property {module:model/DeviceSchemaAddress}
     */
    DeviceSchemaAddress,

    /**
     * The DocumentJsonUpdateSchema model constructor.
     * @property {module:model/DocumentJsonUpdateSchema}
     */
    DocumentJsonUpdateSchema,

    /**
     * The ErrorResponseSchema model constructor.
     * @property {module:model/ErrorResponseSchema}
     */
    ErrorResponseSchema,

    /**
     * The IdentityDocumentJsonSchema model constructor.
     * @property {module:model/IdentityDocumentJsonSchema}
     */
    IdentityDocumentJsonSchema,

    /**
     * The IdentityIdSchema model constructor.
     * @property {module:model/IdentityIdSchema}
     */
    IdentityIdSchema,

    /**
     * The IdentityJsonSchema model constructor.
     * @property {module:model/IdentityJsonSchema}
     */
    IdentityJsonSchema,

    /**
     * The IdentityJsonSchemaDoc model constructor.
     * @property {module:model/IdentityJsonSchemaDoc}
     */
    IdentityJsonSchemaDoc,

    /**
     * The IdentityJsonSchemaDocProof model constructor.
     * @property {module:model/IdentityJsonSchemaDocProof}
     */
    IdentityJsonSchemaDocProof,

    /**
     * The IdentityJsonSchemaDocVerificationMethod model constructor.
     * @property {module:model/IdentityJsonSchemaDocVerificationMethod}
     */
    IdentityJsonSchemaDocVerificationMethod,

    /**
     * The IdentityJsonSchemaKey model constructor.
     * @property {module:model/IdentityJsonSchemaKey}
     */
    IdentityJsonSchemaKey,

    /**
     * The IdentityJsonUpdateSchema model constructor.
     * @property {module:model/IdentityJsonUpdateSchema}
     */
    IdentityJsonUpdateSchema,

    /**
     * The IdentityKeyPairJsonSchema model constructor.
     * @property {module:model/IdentityKeyPairJsonSchema}
     */
    IdentityKeyPairJsonSchema,

    /**
     * The IdentitySchema model constructor.
     * @property {module:model/IdentitySchema}
     */
    IdentitySchema,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse401 model constructor.
     * @property {module:model/InlineResponse401}
     */
    InlineResponse401,

    /**
     * The LatestIdentityJsonSchema model constructor.
     * @property {module:model/LatestIdentityJsonSchema}
     */
    LatestIdentityJsonSchema,

    /**
     * The NonceSchema model constructor.
     * @property {module:model/NonceSchema}
     */
    NonceSchema,

    /**
     * The OrganizationSchema model constructor.
     * @property {module:model/OrganizationSchema}
     */
    OrganizationSchema,

    /**
     * The PersonSchema model constructor.
     * @property {module:model/PersonSchema}
     */
    PersonSchema,

    /**
     * The ProductSchema model constructor.
     * @property {module:model/ProductSchema}
     */
    ProductSchema,

    /**
     * The ProductSchemaAggregateRating model constructor.
     * @property {module:model/ProductSchemaAggregateRating}
     */
    ProductSchemaAggregateRating,

    /**
     * The ProductSchemaAggregateRatingAuthor model constructor.
     * @property {module:model/ProductSchemaAggregateRatingAuthor}
     */
    ProductSchemaAggregateRatingAuthor,

    /**
     * The ProductSchemaManufacturer model constructor.
     * @property {module:model/ProductSchemaManufacturer}
     */
    ProductSchemaManufacturer,

    /**
     * The ProductSchemaReview model constructor.
     * @property {module:model/ProductSchemaReview}
     */
    ProductSchemaReview,

    /**
     * The ProductSchemaReviewReviewRating model constructor.
     * @property {module:model/ProductSchemaReviewReviewRating}
     */
    ProductSchemaReviewReviewRating,

    /**
     * The ProveOwnershipPostBodySchema model constructor.
     * @property {module:model/ProveOwnershipPostBodySchema}
     */
    ProveOwnershipPostBodySchema,

    /**
     * The ReimportBodySchema model constructor.
     * @property {module:model/ReimportBodySchema}
     */
    ReimportBodySchema,

    /**
     * The RequestSubscriptionBodySchema model constructor.
     * @property {module:model/RequestSubscriptionBodySchema}
     */
    RequestSubscriptionBodySchema,

    /**
     * The RequestSubscriptionResponseSchema model constructor.
     * @property {module:model/RequestSubscriptionResponseSchema}
     */
    RequestSubscriptionResponseSchema,

    /**
     * The RevokeSubscriptionBodySchema model constructor.
     * @property {module:model/RevokeSubscriptionBodySchema}
     */
    RevokeSubscriptionBodySchema,

    /**
     * The RevokeVerificationBodySchema model constructor.
     * @property {module:model/RevokeVerificationBodySchema}
     */
    RevokeVerificationBodySchema,

    /**
     * The ServiceSchema model constructor.
     * @property {module:model/ServiceSchema}
     */
    ServiceSchema,

    /**
     * The ServiceSchemaAvailableChannel model constructor.
     * @property {module:model/ServiceSchemaAvailableChannel}
     */
    ServiceSchemaAvailableChannel,

    /**
     * The SubjectBodySchema model constructor.
     * @property {module:model/SubjectBodySchema}
     */
    SubjectBodySchema,

    /**
     * The SubscriptionSchema model constructor.
     * @property {module:model/SubscriptionSchema}
     */
    SubscriptionSchema,

    /**
     * The SubscriptionUpdateSchema model constructor.
     * @property {module:model/SubscriptionUpdateSchema}
     */
    SubscriptionUpdateSchema,

    /**
     * The TopicSchema model constructor.
     * @property {module:model/TopicSchema}
     */
    TopicSchema,

    /**
     * The TrustedRootBodySchema model constructor.
     * @property {module:model/TrustedRootBodySchema}
     */
    TrustedRootBodySchema,

    /**
     * The UpdateIdentityBodySchema model constructor.
     * @property {module:model/UpdateIdentityBodySchema}
     */
    UpdateIdentityBodySchema,

    /**
     * The ValidateBodySchema model constructor.
     * @property {module:model/ValidateBodySchema}
     */
    ValidateBodySchema,

    /**
     * The ValidateBodySchemaInner model constructor.
     * @property {module:model/ValidateBodySchemaInner}
     */
    ValidateBodySchemaInner,

    /**
     * The ValidateResponseSchema model constructor.
     * @property {module:model/ValidateResponseSchema}
     */
    ValidateResponseSchema,

    /**
     * The ValidateResponseSchemaInner model constructor.
     * @property {module:model/ValidateResponseSchemaInner}
     */
    ValidateResponseSchemaInner,

    /**
     * The VerifiableCredentialBodySchema model constructor.
     * @property {module:model/VerifiableCredentialBodySchema}
     */
    VerifiableCredentialBodySchema,

    /**
     * The VerifiableCredentialSchema model constructor.
     * @property {module:model/VerifiableCredentialSchema}
     */
    VerifiableCredentialSchema,

    /**
     * The VerifiableCredentialSubjectSchema model constructor.
     * @property {module:model/VerifiableCredentialSubjectSchema}
     */
    VerifiableCredentialSubjectSchema,

    /**
     * The VerifyIdentityBodySchema model constructor.
     * @property {module:model/VerifyIdentityBodySchema}
     */
    VerifyIdentityBodySchema,

    /**
     * The VerifyIdentityBodySchemaInitiatorVC model constructor.
     * @property {module:model/VerifyIdentityBodySchemaInitiatorVC}
     */
    VerifyIdentityBodySchemaInitiatorVC,

    /**
     * The VerifyIdentityBodySchemaInitiatorVCCredentialSubject model constructor.
     * @property {module:model/VerifyIdentityBodySchemaInitiatorVCCredentialSubject}
     */
    VerifyIdentityBodySchemaInitiatorVCCredentialSubject,

    /**
     * The VerifyIdentityBodySchemaInitiatorVCProof model constructor.
     * @property {module:model/VerifyIdentityBodySchemaInitiatorVCProof}
     */
    VerifyIdentityBodySchemaInitiatorVCProof,

    /**
     * The VerifyIdentityBodySchemaSubject model constructor.
     * @property {module:model/VerifyIdentityBodySchemaSubject}
     */
    VerifyIdentityBodySchemaSubject,

    /**
     * The VerifyIdentityBodySchemaSubjectClaim model constructor.
     * @property {module:model/VerifyIdentityBodySchemaSubjectClaim}
     */
    VerifyIdentityBodySchemaSubjectClaim,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The ChannelInfoApi service constructor.
    * @property {module:api/ChannelInfoApi}
    */
    ChannelInfoApi,

    /**
    * The ChannelsApi service constructor.
    * @property {module:api/ChannelsApi}
    */
    ChannelsApi,

    /**
    * The IdentitiesApi service constructor.
    * @property {module:api/IdentitiesApi}
    */
    IdentitiesApi,

    /**
    * The ServerInfoApi service constructor.
    * @property {module:api/ServerInfoApi}
    */
    ServerInfoApi,

    /**
    * The SubscriptionsApi service constructor.
    * @property {module:api/SubscriptionsApi}
    */
    SubscriptionsApi,

    /**
    * The VerificationApi service constructor.
    * @property {module:api/VerificationApi}
    */
    VerificationApi
};
