/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegrationServicesApiDocumentation);
  }
}(this, function(expect, IntegrationServicesApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntegrationServicesApiDocumentation.ChannelInfoApi();
  });

  describe('(package)', function() {
    describe('ChannelInfoApi', function() {
      describe('channelInfoChannelChannelAddressDelete', function() {
        it('should call channelInfoChannelChannelAddressDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for channelInfoChannelChannelAddressDelete call
          /*

          instance.channelInfoChannelChannelAddressDelete(channelAddress, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('channelInfoChannelChannelAddressGet', function() {
        it('should call channelInfoChannelChannelAddressGet successfully', function(done) {
          // TODO: uncomment, update parameter values for channelInfoChannelChannelAddressGet call and complete the assertions
          /*

          instance.channelInfoChannelChannelAddressGet(channelAddress, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IntegrationServicesApiDocumentation.ChannelInfoSchema);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('channelInfoChannelPost', function() {
        it('should call channelInfoChannelPost successfully', function(done) {
          // TODO: uncomment, update parameter values for channelInfoChannelPost call
          /*
          var opts = {};

          instance.channelInfoChannelPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('channelInfoChannelPut', function() {
        it('should call channelInfoChannelPut successfully', function(done) {
          // TODO: uncomment, update parameter values for channelInfoChannelPut call
          /*
          var opts = {};

          instance.channelInfoChannelPut(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('channelInfoSearchGet', function() {
        it('should call channelInfoSearchGet successfully', function(done) {
          // TODO: uncomment, update parameter values for channelInfoSearchGet call and complete the assertions
          /*
          var opts = {};

          instance.channelInfoSearchGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(IntegrationServicesApiDocumentation.ChannelInfoSchema);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
