/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegrationServicesApiDocumentation);
  }
}(this, function(expect, IntegrationServicesApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChannelInfoSchema', function() {
      beforeEach(function() {
        instance = new IntegrationServicesApiDocumentation.ChannelInfoSchema();
      });

      it('should create an instance of ChannelInfoSchema', function() {
        // TODO: update the code to test ChannelInfoSchema
        expect(instance).to.be.a(IntegrationServicesApiDocumentation.ChannelInfoSchema);
      });

      it('should have the property channelAddress (base name: "channelAddress")', function() {
        // TODO: update the code to test the property channelAddress
        expect(instance).to.have.property('channelAddress');
        // expect(instance.channelAddress).to.be(expectedValueLiteral);
      });

      it('should have the property authorId (base name: "authorId")', function() {
        // TODO: update the code to test the property authorId
        expect(instance).to.have.property('authorId');
        // expect(instance.authorId).to.be(expectedValueLiteral);
      });

      it('should have the property subscriberIds (base name: "subscriberIds")', function() {
        // TODO: update the code to test the property subscriberIds
        expect(instance).to.have.property('subscriberIds');
        // expect(instance.subscriberIds).to.be(expectedValueLiteral);
      });

      it('should have the property topics (base name: "topics")', function() {
        // TODO: update the code to test the property topics
        expect(instance).to.have.property('topics');
        // expect(instance.topics).to.be(expectedValueLiteral);
      });

      it('should have the property created (base name: "created")', function() {
        // TODO: update the code to test the property created
        expect(instance).to.have.property('created');
        // expect(instance.created).to.be(expectedValueLiteral);
      });

      it('should have the property latestMessage (base name: "latestMessage")', function() {
        // TODO: update the code to test the property latestMessage
        expect(instance).to.have.property('latestMessage');
        // expect(instance.latestMessage).to.be(expectedValueLiteral);
      });

    });
  });

}));
