/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegrationServicesApiDocumentation);
  }
}(this, function(expect, IntegrationServicesApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeviceSchemaAddress', function() {
      beforeEach(function() {
        instance = new IntegrationServicesApiDocumentation.DeviceSchemaAddress();
      });

      it('should create an instance of DeviceSchemaAddress', function() {
        // TODO: update the code to test DeviceSchemaAddress
        expect(instance).to.be.a(IntegrationServicesApiDocumentation.DeviceSchemaAddress);
      });

      it('should have the property context (base name: "@context")', function() {
        // TODO: update the code to test the property context
        expect(instance).to.have.property('context');
        // expect(instance.context).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property alternateName (base name: "alternateName")', function() {
        // TODO: update the code to test the property alternateName
        expect(instance).to.have.property('alternateName');
        // expect(instance.alternateName).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property image (base name: "image")', function() {
        // TODO: update the code to test the property image
        expect(instance).to.have.property('image');
        // expect(instance.image).to.be(expectedValueLiteral);
      });

      it('should have the property sameAs (base name: "sameAs")', function() {
        // TODO: update the code to test the property sameAs
        expect(instance).to.have.property('sameAs');
        // expect(instance.sameAs).to.be(expectedValueLiteral);
      });

      it('should have the property addressCountry (base name: "addressCountry")', function() {
        // TODO: update the code to test the property addressCountry
        expect(instance).to.have.property('addressCountry');
        // expect(instance.addressCountry).to.be(expectedValueLiteral);
      });

      it('should have the property addressLocality (base name: "addressLocality")', function() {
        // TODO: update the code to test the property addressLocality
        expect(instance).to.have.property('addressLocality');
        // expect(instance.addressLocality).to.be(expectedValueLiteral);
      });

      it('should have the property addressRegion (base name: "addressRegion")', function() {
        // TODO: update the code to test the property addressRegion
        expect(instance).to.have.property('addressRegion');
        // expect(instance.addressRegion).to.be(expectedValueLiteral);
      });

      it('should have the property postOfficeBoxNumber (base name: "postOfficeBoxNumber")', function() {
        // TODO: update the code to test the property postOfficeBoxNumber
        expect(instance).to.have.property('postOfficeBoxNumber');
        // expect(instance.postOfficeBoxNumber).to.be(expectedValueLiteral);
      });

      it('should have the property postalCode (base name: "postalCode")', function() {
        // TODO: update the code to test the property postalCode
        expect(instance).to.have.property('postalCode');
        // expect(instance.postalCode).to.be(expectedValueLiteral);
      });

      it('should have the property streetAddress (base name: "streetAddress")', function() {
        // TODO: update the code to test the property streetAddress
        expect(instance).to.have.property('streetAddress');
        // expect(instance.streetAddress).to.be(expectedValueLiteral);
      });

    });
  });

}));
