/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegrationServicesApiDocumentation);
  }
}(this, function(expect, IntegrationServicesApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IdentityKeyPairJsonSchema', function() {
      beforeEach(function() {
        instance = new IntegrationServicesApiDocumentation.IdentityKeyPairJsonSchema();
      });

      it('should create an instance of IdentityKeyPairJsonSchema', function() {
        // TODO: update the code to test IdentityKeyPairJsonSchema
        expect(instance).to.be.a(IntegrationServicesApiDocumentation.IdentityKeyPairJsonSchema);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property _public (base name: "public")', function() {
        // TODO: update the code to test the property _public
        expect(instance).to.have.property('_public');
        // expect(instance._public).to.be(expectedValueLiteral);
      });

      it('should have the property secret (base name: "secret")', function() {
        // TODO: update the code to test the property secret
        expect(instance).to.have.property('secret');
        // expect(instance.secret).to.be(expectedValueLiteral);
      });

      it('should have the property encoding (base name: "encoding")', function() {
        // TODO: update the code to test the property encoding
        expect(instance).to.have.property('encoding');
        // expect(instance.encoding).to.be(expectedValueLiteral);
      });

    });
  });

}));
