/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddChannelLogBodySchema model module.
 * @module model/AddChannelLogBodySchema
 * @version 1.0.0
 */
export class AddChannelLogBodySchema {
  /**
   * Constructs a new <code>AddChannelLogBodySchema</code>.
   * @alias module:model/AddChannelLogBodySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddChannelLogBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddChannelLogBodySchema} obj Optional instance to populate.
   * @return {module:model/AddChannelLogBodySchema} The populated <code>AddChannelLogBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddChannelLogBodySchema();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], Object);
      if (data.hasOwnProperty('publicPayload'))
        obj.publicPayload = ApiClient.convertToType(data['publicPayload'], Object);
      if (data.hasOwnProperty('payload'))
        obj.payload = ApiClient.convertToType(data['payload'], Object);
    }
    return obj;
  }
}

/**
 * Public available type.
 * @member {String} type
 */
AddChannelLogBodySchema.prototype.type = undefined;

/**
 * Public available date.
 * @member {Date} created
 */
AddChannelLogBodySchema.prototype.created = undefined;

/**
 * Public available metadata.
 * @member {Object} metadata
 */
AddChannelLogBodySchema.prototype.metadata = undefined;

/**
 * Public available payload.
 * @member {Object} publicPayload
 */
AddChannelLogBodySchema.prototype.publicPayload = undefined;

/**
 * Payload is stored encrypted in the channel.
 * @member {Object} payload
 */
AddChannelLogBodySchema.prototype.payload = undefined;

