/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateChannelBodySchemaTopics} from './CreateChannelBodySchemaTopics';

/**
 * The ChannelInfoSchema model module.
 * @module model/ChannelInfoSchema
 * @version 1.0.0
 */
export class ChannelInfoSchema {
  /**
   * Constructs a new <code>ChannelInfoSchema</code>.
   * @alias module:model/ChannelInfoSchema
   * @class
   * @param channelAddress {String} 
   * @param authorId {String} 
   * @param topics {Array.<module:model/CreateChannelBodySchemaTopics>} 
   */
  constructor(channelAddress, authorId, topics) {
    this.channelAddress = channelAddress;
    this.authorId = authorId;
    this.topics = topics;
  }

  /**
   * Constructs a <code>ChannelInfoSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelInfoSchema} obj Optional instance to populate.
   * @return {module:model/ChannelInfoSchema} The populated <code>ChannelInfoSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChannelInfoSchema();
      if (data.hasOwnProperty('channelAddress'))
        obj.channelAddress = ApiClient.convertToType(data['channelAddress'], 'String');
      if (data.hasOwnProperty('authorId'))
        obj.authorId = ApiClient.convertToType(data['authorId'], 'String');
      if (data.hasOwnProperty('subscriberIds'))
        obj.subscriberIds = ApiClient.convertToType(data['subscriberIds'], ['String']);
      if (data.hasOwnProperty('topics'))
        obj.topics = ApiClient.convertToType(data['topics'], [CreateChannelBodySchemaTopics]);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('latestMessage'))
        obj.latestMessage = ApiClient.convertToType(data['latestMessage'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} channelAddress
 */
ChannelInfoSchema.prototype.channelAddress = undefined;

/**
 * @member {String} authorId
 */
ChannelInfoSchema.prototype.authorId = undefined;

/**
 * @member {Array.<String>} subscriberIds
 */
ChannelInfoSchema.prototype.subscriberIds = undefined;

/**
 * @member {Array.<module:model/CreateChannelBodySchemaTopics>} topics
 */
ChannelInfoSchema.prototype.topics = undefined;

/**
 * @member {Date} created
 */
ChannelInfoSchema.prototype.created = undefined;

/**
 * @member {Date} latestMessage
 */
ChannelInfoSchema.prototype.latestMessage = undefined;

