/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChannelDataSchemaLog} from './ChannelDataSchemaLog';

/**
 * The ChannelDataSchema model module.
 * @module model/ChannelDataSchema
 * @version 1.0.0
 */
export class ChannelDataSchema {
  /**
   * Constructs a new <code>ChannelDataSchema</code>.
   * @alias module:model/ChannelDataSchema
   * @class
   * @param link {String} 
   * @param log {module:model/ChannelDataSchemaLog} 
   */
  constructor(link, log) {
    this.link = link;
    this.log = log;
  }

  /**
   * Constructs a <code>ChannelDataSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelDataSchema} obj Optional instance to populate.
   * @return {module:model/ChannelDataSchema} The populated <code>ChannelDataSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChannelDataSchema();
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('imported'))
        obj.imported = ApiClient.convertToType(data['imported'], 'Date');
      if (data.hasOwnProperty('messageId'))
        obj.messageId = ApiClient.convertToType(data['messageId'], 'String');
      if (data.hasOwnProperty('log'))
        obj.log = ChannelDataSchemaLog.constructFromObject(data['log']);
    }
    return obj;
  }
}

/**
 * @member {String} link
 */
ChannelDataSchema.prototype.link = undefined;

/**
 * Date when the data was imported from the tangle into the cached database.
 * @member {Date} imported
 */
ChannelDataSchema.prototype.imported = undefined;

/**
 * Message id can be used to search for the message in an IOTA explorer.
 * @member {String} messageId
 */
ChannelDataSchema.prototype.messageId = undefined;

/**
 * @member {module:model/ChannelDataSchemaLog} log
 */
ChannelDataSchema.prototype.log = undefined;

