/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateChannelBodySchemaTopics model module.
 * @module model/CreateChannelBodySchemaTopics
 * @version 1.0.0
 */
export class CreateChannelBodySchemaTopics {
  /**
   * Constructs a new <code>CreateChannelBodySchemaTopics</code>.
   * @alias module:model/CreateChannelBodySchemaTopics
   * @class
   * @param type {String} 
   * @param source {String} 
   */
  constructor(type, source) {
    this.type = type;
    this.source = source;
  }

  /**
   * Constructs a <code>CreateChannelBodySchemaTopics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateChannelBodySchemaTopics} obj Optional instance to populate.
   * @return {module:model/CreateChannelBodySchemaTopics} The populated <code>CreateChannelBodySchemaTopics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateChannelBodySchemaTopics();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
CreateChannelBodySchemaTopics.prototype.type = undefined;

/**
 * @member {String} source
 */
CreateChannelBodySchemaTopics.prototype.source = undefined;

