/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateChannelResponseSchema model module.
 * @module model/CreateChannelResponseSchema
 * @version 1.0.0
 */
export class CreateChannelResponseSchema {
  /**
   * Constructs a new <code>CreateChannelResponseSchema</code>.
   * @alias module:model/CreateChannelResponseSchema
   * @class
   * @param channelAddress {String} 
   */
  constructor(channelAddress) {
    this.channelAddress = channelAddress;
  }

  /**
   * Constructs a <code>CreateChannelResponseSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateChannelResponseSchema} obj Optional instance to populate.
   * @return {module:model/CreateChannelResponseSchema} The populated <code>CreateChannelResponseSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateChannelResponseSchema();
      if (data.hasOwnProperty('seed'))
        obj.seed = ApiClient.convertToType(data['seed'], 'String');
      if (data.hasOwnProperty('channelAddress'))
        obj.channelAddress = ApiClient.convertToType(data['channelAddress'], 'String');
      if (data.hasOwnProperty('presharedKey'))
        obj.presharedKey = ApiClient.convertToType(data['presharedKey'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} seed
 */
CreateChannelResponseSchema.prototype.seed = undefined;

/**
 * @member {String} channelAddress
 */
CreateChannelResponseSchema.prototype.channelAddress = undefined;

/**
 * @member {String} presharedKey
 */
CreateChannelResponseSchema.prototype.presharedKey = undefined;

