/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IdentityJsonSchemaDoc} from './IdentityJsonSchemaDoc';
import {IdentityJsonSchemaKey} from './IdentityJsonSchemaKey';

/**
 * The IdentityJsonSchema model module.
 * @module model/IdentityJsonSchema
 * @version 1.0.0
 */
export class IdentityJsonSchema {
  /**
   * Constructs a new <code>IdentityJsonSchema</code>.
   * @alias module:model/IdentityJsonSchema
   * @class
   * @param doc {module:model/IdentityJsonSchemaDoc} 
   * @param key {module:model/IdentityJsonSchemaKey} 
   */
  constructor(doc, key) {
    this.doc = doc;
    this.key = key;
  }

  /**
   * Constructs a <code>IdentityJsonSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityJsonSchema} obj Optional instance to populate.
   * @return {module:model/IdentityJsonSchema} The populated <code>IdentityJsonSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentityJsonSchema();
      if (data.hasOwnProperty('doc'))
        obj.doc = IdentityJsonSchemaDoc.constructFromObject(data['doc']);
      if (data.hasOwnProperty('key'))
        obj.key = IdentityJsonSchemaKey.constructFromObject(data['key']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IdentityJsonSchemaDoc} doc
 */
IdentityJsonSchema.prototype.doc = undefined;

/**
 * @member {module:model/IdentityJsonSchemaKey} key
 */
IdentityJsonSchema.prototype.key = undefined;

