/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IdentityJsonSchemaDoc} from './IdentityJsonSchemaDoc';
import {IdentityJsonSchemaKey} from './IdentityJsonSchemaKey';

/**
 * The IdentityJsonUpdateSchema model module.
 * @module model/IdentityJsonUpdateSchema
 * @version 1.0.0
 */
export class IdentityJsonUpdateSchema {
  /**
   * Constructs a new <code>IdentityJsonUpdateSchema</code>.
   * @alias module:model/IdentityJsonUpdateSchema
   * @class
   * @param doc {module:model/IdentityJsonSchemaDoc} 
   * @param key {module:model/IdentityJsonSchemaKey} 
   * @param txHash {String} 
   */
  constructor(doc, key, txHash) {
    this.doc = doc;
    this.key = key;
    this.txHash = txHash;
  }

  /**
   * Constructs a <code>IdentityJsonUpdateSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityJsonUpdateSchema} obj Optional instance to populate.
   * @return {module:model/IdentityJsonUpdateSchema} The populated <code>IdentityJsonUpdateSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentityJsonUpdateSchema();
      if (data.hasOwnProperty('doc'))
        obj.doc = IdentityJsonSchemaDoc.constructFromObject(data['doc']);
      if (data.hasOwnProperty('key'))
        obj.key = IdentityJsonSchemaKey.constructFromObject(data['key']);
      if (data.hasOwnProperty('txHash'))
        obj.txHash = ApiClient.convertToType(data['txHash'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IdentityJsonSchemaDoc} doc
 */
IdentityJsonUpdateSchema.prototype.doc = undefined;

/**
 * @member {module:model/IdentityJsonSchemaKey} key
 */
IdentityJsonUpdateSchema.prototype.key = undefined;

/**
 * @member {String} txHash
 */
IdentityJsonUpdateSchema.prototype.txHash = undefined;

