/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VerifyIdentityBodySchemaInitiatorVC} from './VerifyIdentityBodySchemaInitiatorVC';
import {VerifyIdentityBodySchemaSubjectClaim} from './VerifyIdentityBodySchemaSubjectClaim';

/**
 * The IdentitySchema model module.
 * @module model/IdentitySchema
 * @version 1.0.0
 */
export class IdentitySchema {
  /**
   * Constructs a new <code>IdentitySchema</code>.
   * @alias module:model/IdentitySchema
   * @class
   * @param identityId {String} 
   * @param publicKey {String} 
   */
  constructor(identityId, publicKey) {
    this.identityId = identityId;
    this.publicKey = publicKey;
  }

  /**
   * Constructs a <code>IdentitySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentitySchema} obj Optional instance to populate.
   * @return {module:model/IdentitySchema} The populated <code>IdentitySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentitySchema();
      if (data.hasOwnProperty('identityId'))
        obj.identityId = ApiClient.convertToType(data['identityId'], 'String');
      if (data.hasOwnProperty('publicKey'))
        obj.publicKey = ApiClient.convertToType(data['publicKey'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('registrationDate'))
        obj.registrationDate = ApiClient.convertToType(data['registrationDate'], 'Date');
      if (data.hasOwnProperty('verifiableCredentials'))
        obj.verifiableCredentials = ApiClient.convertToType(data['verifiableCredentials'], [VerifyIdentityBodySchemaInitiatorVC]);
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('claim'))
        obj.claim = VerifyIdentityBodySchemaSubjectClaim.constructFromObject(data['claim']);
      if (data.hasOwnProperty('isPrivate'))
        obj.isPrivate = ApiClient.convertToType(data['isPrivate'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} identityId
 */
IdentitySchema.prototype.identityId = undefined;

/**
 * @member {String} publicKey
 */
IdentitySchema.prototype.publicKey = undefined;

/**
 * @member {String} username
 */
IdentitySchema.prototype.username = undefined;

/**
 * @member {Date} registrationDate
 */
IdentitySchema.prototype.registrationDate = undefined;

/**
 * @member {Array.<module:model/VerifyIdentityBodySchemaInitiatorVC>} verifiableCredentials
 */
IdentitySchema.prototype.verifiableCredentials = undefined;

/**
 * @member {String} role
 */
IdentitySchema.prototype.role = undefined;

/**
 * @member {module:model/VerifyIdentityBodySchemaSubjectClaim} claim
 */
IdentitySchema.prototype.claim = undefined;

/**
 * @member {Boolean} isPrivate
 */
IdentitySchema.prototype.isPrivate = undefined;

