/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdentityJsonSchemaKey model module.
 * @module model/IdentityJsonSchemaKey
 * @version 1.0.0
 */
export class IdentityJsonSchemaKey {
  /**
   * Constructs a new <code>IdentityJsonSchemaKey</code>.
   * @alias module:model/IdentityJsonSchemaKey
   * @class
   * @param type {String} 
   * @param _public {String} 
   * @param secret {String} 
   * @param encoding {String} 
   */
  constructor(type, _public, secret, encoding) {
    this.type = type;
    this._public = _public;
    this.secret = secret;
    this.encoding = encoding;
  }

  /**
   * Constructs a <code>IdentityJsonSchemaKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityJsonSchemaKey} obj Optional instance to populate.
   * @return {module:model/IdentityJsonSchemaKey} The populated <code>IdentityJsonSchemaKey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentityJsonSchemaKey();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('public'))
        obj._public = ApiClient.convertToType(data['public'], 'String');
      if (data.hasOwnProperty('secret'))
        obj.secret = ApiClient.convertToType(data['secret'], 'String');
      if (data.hasOwnProperty('encoding'))
        obj.encoding = ApiClient.convertToType(data['encoding'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
IdentityJsonSchemaKey.prototype.type = undefined;

/**
 * @member {String} _public
 */
IdentityJsonSchemaKey.prototype._public = undefined;

/**
 * @member {String} secret
 */
IdentityJsonSchemaKey.prototype.secret = undefined;

/**
 * @member {String} encoding
 */
IdentityJsonSchemaKey.prototype.encoding = undefined;

