/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdentityJsonSchemaDocProof model module.
 * @module model/IdentityJsonSchemaDocProof
 * @version 1.0.0
 */
export class IdentityJsonSchemaDocProof {
  /**
   * Constructs a new <code>IdentityJsonSchemaDocProof</code>.
   * @alias module:model/IdentityJsonSchemaDocProof
   * @class
   * @param type {String} 
   * @param verificationMethod {String} 
   * @param signatureValue {String} 
   */
  constructor(type, verificationMethod, signatureValue) {
    this.type = type;
    this.verificationMethod = verificationMethod;
    this.signatureValue = signatureValue;
  }

  /**
   * Constructs a <code>IdentityJsonSchemaDocProof</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityJsonSchemaDocProof} obj Optional instance to populate.
   * @return {module:model/IdentityJsonSchemaDocProof} The populated <code>IdentityJsonSchemaDocProof</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentityJsonSchemaDocProof();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('verificationMethod'))
        obj.verificationMethod = ApiClient.convertToType(data['verificationMethod'], 'String');
      if (data.hasOwnProperty('signatureValue'))
        obj.signatureValue = ApiClient.convertToType(data['signatureValue'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
IdentityJsonSchemaDocProof.prototype.type = undefined;

/**
 * @member {String} verificationMethod
 */
IdentityJsonSchemaDocProof.prototype.verificationMethod = undefined;

/**
 * @member {String} signatureValue
 */
IdentityJsonSchemaDocProof.prototype.signatureValue = undefined;

