/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdentityJsonSchemaDocVerificationMethod model module.
 * @module model/IdentityJsonSchemaDocVerificationMethod
 * @version 1.0.0
 */
export class IdentityJsonSchemaDocVerificationMethod {
  /**
   * Constructs a new <code>IdentityJsonSchemaDocVerificationMethod</code>.
   * @alias module:model/IdentityJsonSchemaDocVerificationMethod
   * @class
   * @param id {String} 
   * @param controller {String} 
   * @param type {String} 
   * @param publicKeyBase58 {String} 
   */
  constructor(id, controller, type, publicKeyBase58) {
    this.id = id;
    this.controller = controller;
    this.type = type;
    this.publicKeyBase58 = publicKeyBase58;
  }

  /**
   * Constructs a <code>IdentityJsonSchemaDocVerificationMethod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityJsonSchemaDocVerificationMethod} obj Optional instance to populate.
   * @return {module:model/IdentityJsonSchemaDocVerificationMethod} The populated <code>IdentityJsonSchemaDocVerificationMethod</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentityJsonSchemaDocVerificationMethod();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('controller'))
        obj.controller = ApiClient.convertToType(data['controller'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('publicKeyBase58'))
        obj.publicKeyBase58 = ApiClient.convertToType(data['publicKeyBase58'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
IdentityJsonSchemaDocVerificationMethod.prototype.id = undefined;

/**
 * @member {String} controller
 */
IdentityJsonSchemaDocVerificationMethod.prototype.controller = undefined;

/**
 * @member {String} type
 */
IdentityJsonSchemaDocVerificationMethod.prototype.type = undefined;

/**
 * @member {String} publicKeyBase58
 */
IdentityJsonSchemaDocVerificationMethod.prototype.publicKeyBase58 = undefined;

