/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IdentityJsonSchemaDoc} from './IdentityJsonSchemaDoc';

/**
 * The LatestIdentityJsonSchema model module.
 * @module model/LatestIdentityJsonSchema
 * @version 1.0.0
 */
export class LatestIdentityJsonSchema {
  /**
   * Constructs a new <code>LatestIdentityJsonSchema</code>.
   * @alias module:model/LatestIdentityJsonSchema
   * @class
   * @param document {module:model/IdentityJsonSchemaDoc} 
   * @param messageId {String} 
   */
  constructor(document, messageId) {
    this.document = document;
    this.messageId = messageId;
  }

  /**
   * Constructs a <code>LatestIdentityJsonSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LatestIdentityJsonSchema} obj Optional instance to populate.
   * @return {module:model/LatestIdentityJsonSchema} The populated <code>LatestIdentityJsonSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LatestIdentityJsonSchema();
      if (data.hasOwnProperty('document'))
        obj.document = IdentityJsonSchemaDoc.constructFromObject(data['document']);
      if (data.hasOwnProperty('messageId'))
        obj.messageId = ApiClient.convertToType(data['messageId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IdentityJsonSchemaDoc} document
 */
LatestIdentityJsonSchema.prototype.document = undefined;

/**
 * @member {String} messageId
 */
LatestIdentityJsonSchema.prototype.messageId = undefined;

