/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductSchemaAggregateRatingAuthor} from './ProductSchemaAggregateRatingAuthor';

/**
 * The ProductSchemaAggregateRating model module.
 * @module model/ProductSchemaAggregateRating
 * @version 1.0.0
 */
export class ProductSchemaAggregateRating {
  /**
   * Constructs a new <code>ProductSchemaAggregateRating</code>.
   * AggregateRating schema, see the specification at: https://schema.org/AggregateRating
   * @alias module:model/ProductSchemaAggregateRating
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductSchemaAggregateRating</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSchemaAggregateRating} obj Optional instance to populate.
   * @return {module:model/ProductSchemaAggregateRating} The populated <code>ProductSchemaAggregateRating</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductSchemaAggregateRating();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('alternateName'))
        obj.alternateName = ApiClient.convertToType(data['alternateName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('sameAs'))
        obj.sameAs = ApiClient.convertToType(data['sameAs'], Object);
      if (data.hasOwnProperty('author'))
        obj.author = ProductSchemaAggregateRatingAuthor.constructFromObject(data['author']);
      if (data.hasOwnProperty('bestRating'))
        obj.bestRating = ApiClient.convertToType(data['bestRating'], Object);
      if (data.hasOwnProperty('worstRating'))
        obj.worstRating = ApiClient.convertToType(data['worstRating'], Object);
      if (data.hasOwnProperty('itemReviewed'))
        obj.itemReviewed = ProductSchemaAggregateRatingAuthor.constructFromObject(data['itemReviewed']);
      if (data.hasOwnProperty('ratingExplanation'))
        obj.ratingExplanation = ApiClient.convertToType(data['ratingExplanation'], 'String');
      if (data.hasOwnProperty('ratingValue'))
        obj.ratingValue = ApiClient.convertToType(data['ratingValue'], Object);
      if (data.hasOwnProperty('reviewCount'))
        obj.reviewCount = ApiClient.convertToType(data['reviewCount'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
ProductSchemaAggregateRating.prototype.context = undefined;

/**
 * @member {String} type
 */
ProductSchemaAggregateRating.prototype.type = undefined;

/**
 * @member {String} alternateName
 */
ProductSchemaAggregateRating.prototype.alternateName = undefined;

/**
 * @member {String} name
 */
ProductSchemaAggregateRating.prototype.name = undefined;

/**
 * @member {String} description
 */
ProductSchemaAggregateRating.prototype.description = undefined;

/**
 * @member {String} url
 */
ProductSchemaAggregateRating.prototype.url = undefined;

/**
 * @member {Object} image
 */
ProductSchemaAggregateRating.prototype.image = undefined;

/**
 * @member {Object} sameAs
 */
ProductSchemaAggregateRating.prototype.sameAs = undefined;

/**
 * @member {module:model/ProductSchemaAggregateRatingAuthor} author
 */
ProductSchemaAggregateRating.prototype.author = undefined;

/**
 * @member {Object} bestRating
 */
ProductSchemaAggregateRating.prototype.bestRating = undefined;

/**
 * @member {Object} worstRating
 */
ProductSchemaAggregateRating.prototype.worstRating = undefined;

/**
 * @member {module:model/ProductSchemaAggregateRatingAuthor} itemReviewed
 */
ProductSchemaAggregateRating.prototype.itemReviewed = undefined;

/**
 * @member {String} ratingExplanation
 */
ProductSchemaAggregateRating.prototype.ratingExplanation = undefined;

/**
 * @member {Object} ratingValue
 */
ProductSchemaAggregateRating.prototype.ratingValue = undefined;

/**
 * @member {Object} reviewCount
 */
ProductSchemaAggregateRating.prototype.reviewCount = undefined;

