/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductSchemaAggregateRating} from './ProductSchemaAggregateRating';
import {ProductSchemaManufacturer} from './ProductSchemaManufacturer';
import {ProductSchemaReview} from './ProductSchemaReview';

/**
 * The ProductSchema model module.
 * @module model/ProductSchema
 * @version 1.0.0
 */
export class ProductSchema {
  /**
   * Constructs a new <code>ProductSchema</code>.
   * Product schema, see the specification at: https://schema.org/Product
   * @alias module:model/ProductSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSchema} obj Optional instance to populate.
   * @return {module:model/ProductSchema} The populated <code>ProductSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductSchema();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('alternateName'))
        obj.alternateName = ApiClient.convertToType(data['alternateName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('sameAs'))
        obj.sameAs = ApiClient.convertToType(data['sameAs'], Object);
      if (data.hasOwnProperty('aggregateRating'))
        obj.aggregateRating = ProductSchemaAggregateRating.constructFromObject(data['aggregateRating']);
      if (data.hasOwnProperty('award'))
        obj.award = ApiClient.convertToType(data['award'], 'String');
      if (data.hasOwnProperty('brand'))
        obj.brand = ApiClient.convertToType(data['brand'], Object);
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], ['String']);
      if (data.hasOwnProperty('color'))
        obj.color = ApiClient.convertToType(data['color'], 'String');
      if (data.hasOwnProperty('gtin'))
        obj.gtin = ApiClient.convertToType(data['gtin'], 'String');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], Object);
      if (data.hasOwnProperty('logo'))
        obj.logo = ApiClient.convertToType(data['logo'], 'String');
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ProductSchemaManufacturer.constructFromObject(data['manufacturer']);
      if (data.hasOwnProperty('material'))
        obj.material = ApiClient.convertToType(data['material'], Object);
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('mpn'))
        obj.mpn = ApiClient.convertToType(data['mpn'], 'String');
      if (data.hasOwnProperty('nsn'))
        obj.nsn = ApiClient.convertToType(data['nsn'], 'String');
      if (data.hasOwnProperty('offers'))
        obj.offers = ApiClient.convertToType(data['offers'], Object);
      if (data.hasOwnProperty('pattern'))
        obj.pattern = ApiClient.convertToType(data['pattern'], 'String');
      if (data.hasOwnProperty('productID'))
        obj.productID = ApiClient.convertToType(data['productID'], 'String');
      if (data.hasOwnProperty('productionDate'))
        obj.productionDate = ApiClient.convertToType(data['productionDate'], 'Date');
      if (data.hasOwnProperty('purchaseDate'))
        obj.purchaseDate = ApiClient.convertToType(data['purchaseDate'], 'Date');
      if (data.hasOwnProperty('releaseDate'))
        obj.releaseDate = ApiClient.convertToType(data['releaseDate'], 'Date');
      if (data.hasOwnProperty('review'))
        obj.review = ProductSchemaReview.constructFromObject(data['review']);
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], Object);
      if (data.hasOwnProperty('sku'))
        obj.sku = ApiClient.convertToType(data['sku'], 'String');
      if (data.hasOwnProperty('slogan'))
        obj.slogan = ApiClient.convertToType(data['slogan'], 'String');
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], Object);
      if (data.hasOwnProperty('width'))
        obj.width = ApiClient.convertToType(data['width'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
ProductSchema.prototype.context = undefined;

/**
 * @member {String} type
 */
ProductSchema.prototype.type = undefined;

/**
 * @member {String} alternateName
 */
ProductSchema.prototype.alternateName = undefined;

/**
 * @member {String} name
 */
ProductSchema.prototype.name = undefined;

/**
 * @member {String} description
 */
ProductSchema.prototype.description = undefined;

/**
 * @member {String} url
 */
ProductSchema.prototype.url = undefined;

/**
 * @member {Object} image
 */
ProductSchema.prototype.image = undefined;

/**
 * @member {Object} sameAs
 */
ProductSchema.prototype.sameAs = undefined;

/**
 * @member {module:model/ProductSchemaAggregateRating} aggregateRating
 */
ProductSchema.prototype.aggregateRating = undefined;

/**
 * @member {String} award
 */
ProductSchema.prototype.award = undefined;

/**
 * @member {Object} brand
 */
ProductSchema.prototype.brand = undefined;

/**
 * @member {Array.<String>} category
 */
ProductSchema.prototype.category = undefined;

/**
 * @member {String} color
 */
ProductSchema.prototype.color = undefined;

/**
 * @member {String} gtin
 */
ProductSchema.prototype.gtin = undefined;

/**
 * @member {Object} height
 */
ProductSchema.prototype.height = undefined;

/**
 * @member {String} logo
 */
ProductSchema.prototype.logo = undefined;

/**
 * @member {module:model/ProductSchemaManufacturer} manufacturer
 */
ProductSchema.prototype.manufacturer = undefined;

/**
 * @member {Object} material
 */
ProductSchema.prototype.material = undefined;

/**
 * @member {String} model
 */
ProductSchema.prototype.model = undefined;

/**
 * @member {String} mpn
 */
ProductSchema.prototype.mpn = undefined;

/**
 * @member {String} nsn
 */
ProductSchema.prototype.nsn = undefined;

/**
 * @member {Object} offers
 */
ProductSchema.prototype.offers = undefined;

/**
 * @member {String} pattern
 */
ProductSchema.prototype.pattern = undefined;

/**
 * @member {String} productID
 */
ProductSchema.prototype.productID = undefined;

/**
 * @member {Date} productionDate
 */
ProductSchema.prototype.productionDate = undefined;

/**
 * @member {Date} purchaseDate
 */
ProductSchema.prototype.purchaseDate = undefined;

/**
 * @member {Date} releaseDate
 */
ProductSchema.prototype.releaseDate = undefined;

/**
 * @member {module:model/ProductSchemaReview} review
 */
ProductSchema.prototype.review = undefined;

/**
 * @member {Object} size
 */
ProductSchema.prototype.size = undefined;

/**
 * @member {String} sku
 */
ProductSchema.prototype.sku = undefined;

/**
 * @member {String} slogan
 */
ProductSchema.prototype.slogan = undefined;

/**
 * @member {Object} weight
 */
ProductSchema.prototype.weight = undefined;

/**
 * @member {Object} width
 */
ProductSchema.prototype.width = undefined;

