/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductSchemaAggregateRatingAuthor} from './ProductSchemaAggregateRatingAuthor';
import {ProductSchemaReviewReviewRating} from './ProductSchemaReviewReviewRating';

/**
 * The ProductSchemaReview model module.
 * @module model/ProductSchemaReview
 * @version 1.0.0
 */
export class ProductSchemaReview {
  /**
   * Constructs a new <code>ProductSchemaReview</code>.
   * Review schema, see the specification at: https://schema.org/Review
   * @alias module:model/ProductSchemaReview
   * @class
   * @param reviewRating {module:model/ProductSchemaReviewReviewRating} 
   */
  constructor(reviewRating) {
    this.reviewRating = reviewRating;
  }

  /**
   * Constructs a <code>ProductSchemaReview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSchemaReview} obj Optional instance to populate.
   * @return {module:model/ProductSchemaReview} The populated <code>ProductSchemaReview</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductSchemaReview();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('alternateName'))
        obj.alternateName = ApiClient.convertToType(data['alternateName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('sameAs'))
        obj.sameAs = ApiClient.convertToType(data['sameAs'], Object);
      if (data.hasOwnProperty('itemReviewed'))
        obj.itemReviewed = ProductSchemaAggregateRatingAuthor.constructFromObject(data['itemReviewed']);
      if (data.hasOwnProperty('reviewAspect'))
        obj.reviewAspect = ApiClient.convertToType(data['reviewAspect'], 'String');
      if (data.hasOwnProperty('reviewBody'))
        obj.reviewBody = ApiClient.convertToType(data['reviewBody'], 'String');
      if (data.hasOwnProperty('reviewRating'))
        obj.reviewRating = ProductSchemaReviewReviewRating.constructFromObject(data['reviewRating']);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
ProductSchemaReview.prototype.context = undefined;

/**
 * @member {String} type
 */
ProductSchemaReview.prototype.type = undefined;

/**
 * @member {String} alternateName
 */
ProductSchemaReview.prototype.alternateName = undefined;

/**
 * @member {String} name
 */
ProductSchemaReview.prototype.name = undefined;

/**
 * @member {String} description
 */
ProductSchemaReview.prototype.description = undefined;

/**
 * @member {String} url
 */
ProductSchemaReview.prototype.url = undefined;

/**
 * @member {Object} image
 */
ProductSchemaReview.prototype.image = undefined;

/**
 * @member {Object} sameAs
 */
ProductSchemaReview.prototype.sameAs = undefined;

/**
 * @member {module:model/ProductSchemaAggregateRatingAuthor} itemReviewed
 */
ProductSchemaReview.prototype.itemReviewed = undefined;

/**
 * @member {String} reviewAspect
 */
ProductSchemaReview.prototype.reviewAspect = undefined;

/**
 * @member {String} reviewBody
 */
ProductSchemaReview.prototype.reviewBody = undefined;

/**
 * @member {module:model/ProductSchemaReviewReviewRating} reviewRating
 */
ProductSchemaReview.prototype.reviewRating = undefined;

