/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProductSchemaAggregateRatingAuthor model module.
 * @module model/ProductSchemaAggregateRatingAuthor
 * @version 1.0.0
 */
export class ProductSchemaAggregateRatingAuthor {
  /**
   * Constructs a new <code>ProductSchemaAggregateRatingAuthor</code>.
   * @alias module:model/ProductSchemaAggregateRatingAuthor
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductSchemaAggregateRatingAuthor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSchemaAggregateRatingAuthor} obj Optional instance to populate.
   * @return {module:model/ProductSchemaAggregateRatingAuthor} The populated <code>ProductSchemaAggregateRatingAuthor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductSchemaAggregateRatingAuthor();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('alternateName'))
        obj.alternateName = ApiClient.convertToType(data['alternateName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('sameAs'))
        obj.sameAs = ApiClient.convertToType(data['sameAs'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
ProductSchemaAggregateRatingAuthor.prototype.context = undefined;

/**
 * @member {String} type
 */
ProductSchemaAggregateRatingAuthor.prototype.type = undefined;

/**
 * @member {String} alternateName
 */
ProductSchemaAggregateRatingAuthor.prototype.alternateName = undefined;

/**
 * @member {String} name
 */
ProductSchemaAggregateRatingAuthor.prototype.name = undefined;

/**
 * @member {String} description
 */
ProductSchemaAggregateRatingAuthor.prototype.description = undefined;

/**
 * @member {String} url
 */
ProductSchemaAggregateRatingAuthor.prototype.url = undefined;

/**
 * @member {Object} image
 */
ProductSchemaAggregateRatingAuthor.prototype.image = undefined;

/**
 * @member {Object} sameAs
 */
ProductSchemaAggregateRatingAuthor.prototype.sameAs = undefined;

