/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProveOwnershipPostBodySchema model module.
 * @module model/ProveOwnershipPostBodySchema
 * @version 1.0.0
 */
export class ProveOwnershipPostBodySchema {
  /**
   * Constructs a new <code>ProveOwnershipPostBodySchema</code>.
   * @alias module:model/ProveOwnershipPostBodySchema
   * @class
   * @param signedNonce {String} 
   */
  constructor(signedNonce) {
    this.signedNonce = signedNonce;
  }

  /**
   * Constructs a <code>ProveOwnershipPostBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProveOwnershipPostBodySchema} obj Optional instance to populate.
   * @return {module:model/ProveOwnershipPostBodySchema} The populated <code>ProveOwnershipPostBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProveOwnershipPostBodySchema();
      if (data.hasOwnProperty('signedNonce'))
        obj.signedNonce = ApiClient.convertToType(data['signedNonce'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} signedNonce
 */
ProveOwnershipPostBodySchema.prototype.signedNonce = undefined;

