/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReimportBodySchema model module.
 * @module model/ReimportBodySchema
 * @version 1.0.0
 */
export class ReimportBodySchema {
  /**
   * Constructs a new <code>ReimportBodySchema</code>.
   * @alias module:model/ReimportBodySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReimportBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReimportBodySchema} obj Optional instance to populate.
   * @return {module:model/ReimportBodySchema} The populated <code>ReimportBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReimportBodySchema();
      if (data.hasOwnProperty('seed'))
        obj.seed = ApiClient.convertToType(data['seed'], 'String');
      if (data.hasOwnProperty('subscriptionPassword'))
        obj.subscriptionPassword = ApiClient.convertToType(data['subscriptionPassword'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} seed
 */
ReimportBodySchema.prototype.seed = undefined;

/**
 * If a subscriptionPassword is set, all data is encrypted with the password. It need to be made sure, the subscription password is sent when interacting with the APIs of the channel-service and subscription-service.
 * @member {String} subscriptionPassword
 */
ReimportBodySchema.prototype.subscriptionPassword = undefined;

