/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RequestSubscriptionBodySchema model module.
 * @module model/RequestSubscriptionBodySchema
 * @version 1.0.0
 */
export class RequestSubscriptionBodySchema {
  /**
   * Constructs a new <code>RequestSubscriptionBodySchema</code>.
   * @alias module:model/RequestSubscriptionBodySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RequestSubscriptionBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestSubscriptionBodySchema} obj Optional instance to populate.
   * @return {module:model/RequestSubscriptionBodySchema} The populated <code>RequestSubscriptionBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestSubscriptionBodySchema();
      if (data.hasOwnProperty('seed'))
        obj.seed = ApiClient.convertToType(data['seed'], 'String');
      if (data.hasOwnProperty('accessRights'))
        obj.accessRights = ApiClient.convertToType(data['accessRights'], 'String');
      if (data.hasOwnProperty('presharedKey'))
        obj.presharedKey = ApiClient.convertToType(data['presharedKey'], 'String');
    }
    return obj;
  }
}

/**
 * If left empty the api will generate a seed. Make sure you store the seed since the API will not store it. You can reuse your seed for different channels.
 * @member {String} seed
 */
RequestSubscriptionBodySchema.prototype.seed = undefined;

/**
 * @member {String} accessRights
 */
RequestSubscriptionBodySchema.prototype.accessRights = undefined;

/**
 * @member {String} presharedKey
 */
RequestSubscriptionBodySchema.prototype.presharedKey = undefined;

