/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RevokeVerificationBodySchema model module.
 * @module model/RevokeVerificationBodySchema
 * @version 1.0.0
 */
export class RevokeVerificationBodySchema {
  /**
   * Constructs a new <code>RevokeVerificationBodySchema</code>.
   * @alias module:model/RevokeVerificationBodySchema
   * @class
   * @param signatureValue {String} 
   */
  constructor(signatureValue) {
    this.signatureValue = signatureValue;
  }

  /**
   * Constructs a <code>RevokeVerificationBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevokeVerificationBodySchema} obj Optional instance to populate.
   * @return {module:model/RevokeVerificationBodySchema} The populated <code>RevokeVerificationBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RevokeVerificationBodySchema();
      if (data.hasOwnProperty('signatureValue'))
        obj.signatureValue = ApiClient.convertToType(data['signatureValue'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} signatureValue
 */
RevokeVerificationBodySchema.prototype.signatureValue = undefined;

