/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RevokeSubscriptionBodySchema model module.
 * @module model/RevokeSubscriptionBodySchema
 * @version 1.0.0
 */
export class RevokeSubscriptionBodySchema {
  /**
   * Constructs a new <code>RevokeSubscriptionBodySchema</code>.
   * @alias module:model/RevokeSubscriptionBodySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RevokeSubscriptionBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevokeSubscriptionBodySchema} obj Optional instance to populate.
   * @return {module:model/RevokeSubscriptionBodySchema} The populated <code>RevokeSubscriptionBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RevokeSubscriptionBodySchema();
      if (data.hasOwnProperty('subscriptionLink'))
        obj.subscriptionLink = ApiClient.convertToType(data['subscriptionLink'], 'String');
      if (data.hasOwnProperty('identityId'))
        obj.identityId = ApiClient.convertToType(data['identityId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} subscriptionLink
 */
RevokeSubscriptionBodySchema.prototype.subscriptionLink = undefined;

/**
 * @member {String} identityId
 */
RevokeSubscriptionBodySchema.prototype.identityId = undefined;

