/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductSchemaAggregateRating} from './ProductSchemaAggregateRating';
import {ServiceSchemaAvailableChannel} from './ServiceSchemaAvailableChannel';

/**
 * The ServiceSchema model module.
 * @module model/ServiceSchema
 * @version 1.0.0
 */
export class ServiceSchema {
  /**
   * Constructs a new <code>ServiceSchema</code>.
   * Service schema, see the specification at: https://schema.org/Service
   * @alias module:model/ServiceSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ServiceSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceSchema} obj Optional instance to populate.
   * @return {module:model/ServiceSchema} The populated <code>ServiceSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceSchema();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('alternateName'))
        obj.alternateName = ApiClient.convertToType(data['alternateName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('sameAs'))
        obj.sameAs = ApiClient.convertToType(data['sameAs'], Object);
      if (data.hasOwnProperty('aggregateRating'))
        obj.aggregateRating = ProductSchemaAggregateRating.constructFromObject(data['aggregateRating']);
      if (data.hasOwnProperty('availableChannel'))
        obj.availableChannel = ServiceSchemaAvailableChannel.constructFromObject(data['availableChannel']);
      if (data.hasOwnProperty('brand'))
        obj.brand = ApiClient.convertToType(data['brand'], Object);
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('offers'))
        obj.offers = ApiClient.convertToType(data['offers'], Object);
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], Object);
      if (data.hasOwnProperty('review'))
        obj.review = ApiClient.convertToType(data['review'], Object);
      if (data.hasOwnProperty('serviceOutput'))
        obj.serviceOutput = ApiClient.convertToType(data['serviceOutput'], Object);
      if (data.hasOwnProperty('serviceType'))
        obj.serviceType = ApiClient.convertToType(data['serviceType'], 'String');
      if (data.hasOwnProperty('termsOfService'))
        obj.termsOfService = ApiClient.convertToType(data['termsOfService'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
ServiceSchema.prototype.context = undefined;

/**
 * @member {String} type
 */
ServiceSchema.prototype.type = undefined;

/**
 * @member {String} alternateName
 */
ServiceSchema.prototype.alternateName = undefined;

/**
 * @member {String} name
 */
ServiceSchema.prototype.name = undefined;

/**
 * @member {String} description
 */
ServiceSchema.prototype.description = undefined;

/**
 * @member {String} url
 */
ServiceSchema.prototype.url = undefined;

/**
 * @member {Object} image
 */
ServiceSchema.prototype.image = undefined;

/**
 * @member {Object} sameAs
 */
ServiceSchema.prototype.sameAs = undefined;

/**
 * @member {module:model/ProductSchemaAggregateRating} aggregateRating
 */
ServiceSchema.prototype.aggregateRating = undefined;

/**
 * @member {module:model/ServiceSchemaAvailableChannel} availableChannel
 */
ServiceSchema.prototype.availableChannel = undefined;

/**
 * @member {Object} brand
 */
ServiceSchema.prototype.brand = undefined;

/**
 * @member {String} category
 */
ServiceSchema.prototype.category = undefined;

/**
 * @member {Object} offers
 */
ServiceSchema.prototype.offers = undefined;

/**
 * @member {Object} provider
 */
ServiceSchema.prototype.provider = undefined;

/**
 * @member {Object} review
 */
ServiceSchema.prototype.review = undefined;

/**
 * @member {Object} serviceOutput
 */
ServiceSchema.prototype.serviceOutput = undefined;

/**
 * @member {String} serviceType
 */
ServiceSchema.prototype.serviceType = undefined;

/**
 * @member {String} termsOfService
 */
ServiceSchema.prototype.termsOfService = undefined;

