/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VerifyIdentityBodySchemaSubjectClaim} from './VerifyIdentityBodySchemaSubjectClaim';

/**
 * The SubjectBodySchema model module.
 * @module model/SubjectBodySchema
 * @version 1.0.0
 */
export class SubjectBodySchema {
  /**
   * Constructs a new <code>SubjectBodySchema</code>.
   * @alias module:model/SubjectBodySchema
   * @class
   * @param identityId {String} 
   * @param credentialType {String} 
   * @param claim {module:model/VerifyIdentityBodySchemaSubjectClaim} 
   */
  constructor(identityId, credentialType, claim) {
    this.identityId = identityId;
    this.credentialType = credentialType;
    this.claim = claim;
  }

  /**
   * Constructs a <code>SubjectBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubjectBodySchema} obj Optional instance to populate.
   * @return {module:model/SubjectBodySchema} The populated <code>SubjectBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubjectBodySchema();
      if (data.hasOwnProperty('identityId'))
        obj.identityId = ApiClient.convertToType(data['identityId'], 'String');
      if (data.hasOwnProperty('credentialType'))
        obj.credentialType = ApiClient.convertToType(data['credentialType'], 'String');
      if (data.hasOwnProperty('claim'))
        obj.claim = VerifyIdentityBodySchemaSubjectClaim.constructFromObject(data['claim']);
    }
    return obj;
  }
}

/**
 * @member {String} identityId
 */
SubjectBodySchema.prototype.identityId = undefined;

/**
 * @member {String} credentialType
 */
SubjectBodySchema.prototype.credentialType = undefined;

/**
 * @member {module:model/VerifyIdentityBodySchemaSubjectClaim} claim
 */
SubjectBodySchema.prototype.claim = undefined;

