/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SubscriptionUpdateSchema model module.
 * @module model/SubscriptionUpdateSchema
 * @version 1.0.0
 */
export class SubscriptionUpdateSchema {
  /**
   * Constructs a new <code>SubscriptionUpdateSchema</code>.
   * @alias module:model/SubscriptionUpdateSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubscriptionUpdateSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionUpdateSchema} obj Optional instance to populate.
   * @return {module:model/SubscriptionUpdateSchema} The populated <code>SubscriptionUpdateSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionUpdateSchema();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('channelAddress'))
        obj.channelAddress = ApiClient.convertToType(data['channelAddress'], 'String');
      if (data.hasOwnProperty('identityId'))
        obj.identityId = ApiClient.convertToType(data['identityId'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('subscriptionLink'))
        obj.subscriptionLink = ApiClient.convertToType(data['subscriptionLink'], 'String');
      if (data.hasOwnProperty('isAuthorized'))
        obj.isAuthorized = ApiClient.convertToType(data['isAuthorized'], 'Boolean');
      if (data.hasOwnProperty('accessRights'))
        obj.accessRights = ApiClient.convertToType(data['accessRights'], 'String');
      if (data.hasOwnProperty('publicKey'))
        obj.publicKey = ApiClient.convertToType(data['publicKey'], 'String');
      if (data.hasOwnProperty('keyloadLink'))
        obj.keyloadLink = ApiClient.convertToType(data['keyloadLink'], 'String');
      if (data.hasOwnProperty('sequenceLink'))
        obj.sequenceLink = ApiClient.convertToType(data['sequenceLink'], 'String');
      if (data.hasOwnProperty('pskId'))
        obj.pskId = ApiClient.convertToType(data['pskId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
SubscriptionUpdateSchema.prototype.type = undefined;

/**
 * @member {String} channelAddress
 */
SubscriptionUpdateSchema.prototype.channelAddress = undefined;

/**
 * @member {String} identityId
 */
SubscriptionUpdateSchema.prototype.identityId = undefined;

/**
 * @member {String} state
 */
SubscriptionUpdateSchema.prototype.state = undefined;

/**
 * @member {String} subscriptionLink
 */
SubscriptionUpdateSchema.prototype.subscriptionLink = undefined;

/**
 * @member {Boolean} isAuthorized
 */
SubscriptionUpdateSchema.prototype.isAuthorized = undefined;

/**
 * @member {String} accessRights
 */
SubscriptionUpdateSchema.prototype.accessRights = undefined;

/**
 * @member {String} publicKey
 */
SubscriptionUpdateSchema.prototype.publicKey = undefined;

/**
 * @member {String} keyloadLink
 */
SubscriptionUpdateSchema.prototype.keyloadLink = undefined;

/**
 * @member {String} sequenceLink
 */
SubscriptionUpdateSchema.prototype.sequenceLink = undefined;

/**
 * @member {String} pskId
 */
SubscriptionUpdateSchema.prototype.pskId = undefined;

