/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SubscriptionSchema model module.
 * @module model/SubscriptionSchema
 * @version 1.0.0
 */
export class SubscriptionSchema {
  /**
   * Constructs a new <code>SubscriptionSchema</code>.
   * @alias module:model/SubscriptionSchema
   * @class
   * @param type {String} 
   * @param channelAddress {String} 
   * @param identityId {String} 
   * @param state {String} 
   * @param isAuthorized {Boolean} 
   * @param accessRights {String} 
   */
  constructor(type, channelAddress, identityId, state, isAuthorized, accessRights) {
    this.type = type;
    this.channelAddress = channelAddress;
    this.identityId = identityId;
    this.state = state;
    this.isAuthorized = isAuthorized;
    this.accessRights = accessRights;
  }

  /**
   * Constructs a <code>SubscriptionSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionSchema} obj Optional instance to populate.
   * @return {module:model/SubscriptionSchema} The populated <code>SubscriptionSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionSchema();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('channelAddress'))
        obj.channelAddress = ApiClient.convertToType(data['channelAddress'], 'String');
      if (data.hasOwnProperty('identityId'))
        obj.identityId = ApiClient.convertToType(data['identityId'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('subscriptionLink'))
        obj.subscriptionLink = ApiClient.convertToType(data['subscriptionLink'], 'String');
      if (data.hasOwnProperty('isAuthorized'))
        obj.isAuthorized = ApiClient.convertToType(data['isAuthorized'], 'Boolean');
      if (data.hasOwnProperty('accessRights'))
        obj.accessRights = ApiClient.convertToType(data['accessRights'], 'String');
      if (data.hasOwnProperty('publicKey'))
        obj.publicKey = ApiClient.convertToType(data['publicKey'], 'String');
      if (data.hasOwnProperty('keyloadLink'))
        obj.keyloadLink = ApiClient.convertToType(data['keyloadLink'], 'String');
      if (data.hasOwnProperty('sequenceLink'))
        obj.sequenceLink = ApiClient.convertToType(data['sequenceLink'], 'String');
      if (data.hasOwnProperty('pskId'))
        obj.pskId = ApiClient.convertToType(data['pskId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
SubscriptionSchema.prototype.type = undefined;

/**
 * @member {String} channelAddress
 */
SubscriptionSchema.prototype.channelAddress = undefined;

/**
 * @member {String} identityId
 */
SubscriptionSchema.prototype.identityId = undefined;

/**
 * @member {String} state
 */
SubscriptionSchema.prototype.state = undefined;

/**
 * @member {String} subscriptionLink
 */
SubscriptionSchema.prototype.subscriptionLink = undefined;

/**
 * @member {Boolean} isAuthorized
 */
SubscriptionSchema.prototype.isAuthorized = undefined;

/**
 * @member {String} accessRights
 */
SubscriptionSchema.prototype.accessRights = undefined;

/**
 * @member {String} publicKey
 */
SubscriptionSchema.prototype.publicKey = undefined;

/**
 * @member {String} keyloadLink
 */
SubscriptionSchema.prototype.keyloadLink = undefined;

/**
 * @member {String} sequenceLink
 */
SubscriptionSchema.prototype.sequenceLink = undefined;

/**
 * @member {String} pskId
 */
SubscriptionSchema.prototype.pskId = undefined;

