/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ValidateResponseSchemaInner model module.
 * @module model/ValidateResponseSchemaInner
 * @version 1.0.0
 */
export class ValidateResponseSchemaInner {
  /**
   * Constructs a new <code>ValidateResponseSchemaInner</code>.
   * @alias module:model/ValidateResponseSchemaInner
   * @class
   * @param link {String} 
   * @param isValid {Boolean} 
   */
  constructor(link, isValid) {
    this.link = link;
    this.isValid = isValid;
  }

  /**
   * Constructs a <code>ValidateResponseSchemaInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidateResponseSchemaInner} obj Optional instance to populate.
   * @return {module:model/ValidateResponseSchemaInner} The populated <code>ValidateResponseSchemaInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ValidateResponseSchemaInner();
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('isValid'))
        obj.isValid = ApiClient.convertToType(data['isValid'], 'Boolean');
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
      if (data.hasOwnProperty('tangleLog'))
        obj.tangleLog = ApiClient.convertToType(data['tangleLog'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} link
 */
ValidateResponseSchemaInner.prototype.link = undefined;

/**
 * @member {Boolean} isValid
 */
ValidateResponseSchemaInner.prototype.isValid = undefined;

/**
 * @member {String} error
 */
ValidateResponseSchemaInner.prototype.error = undefined;

/**
 * @member {Object} tangleLog
 */
ValidateResponseSchemaInner.prototype.tangleLog = undefined;

