/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VerifyIdentityBodySchemaInitiatorVCCredentialSubject} from './VerifyIdentityBodySchemaInitiatorVCCredentialSubject';
import {VerifyIdentityBodySchemaInitiatorVCProof} from './VerifyIdentityBodySchemaInitiatorVCProof';

/**
 * The VerifiableCredentialSchema model module.
 * @module model/VerifiableCredentialSchema
 * @version 1.0.0
 */
export class VerifiableCredentialSchema {
  /**
   * Constructs a new <code>VerifiableCredentialSchema</code>.
   * @alias module:model/VerifiableCredentialSchema
   * @class
   * @param context {String} 
   * @param id {String} 
   * @param type {Array.<String>} 
   * @param credentialSubject {module:model/VerifyIdentityBodySchemaInitiatorVCCredentialSubject} 
   * @param issuer {String} 
   * @param issuanceDate {Date} 
   * @param proof {module:model/VerifyIdentityBodySchemaInitiatorVCProof} 
   */
  constructor(context, id, type, credentialSubject, issuer, issuanceDate, proof) {
    this.context = context;
    this.id = id;
    this.type = type;
    this.credentialSubject = credentialSubject;
    this.issuer = issuer;
    this.issuanceDate = issuanceDate;
    this.proof = proof;
  }

  /**
   * Constructs a <code>VerifiableCredentialSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifiableCredentialSchema} obj Optional instance to populate.
   * @return {module:model/VerifiableCredentialSchema} The populated <code>VerifiableCredentialSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerifiableCredentialSchema();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], ['String']);
      if (data.hasOwnProperty('credentialSubject'))
        obj.credentialSubject = VerifyIdentityBodySchemaInitiatorVCCredentialSubject.constructFromObject(data['credentialSubject']);
      if (data.hasOwnProperty('issuer'))
        obj.issuer = ApiClient.convertToType(data['issuer'], 'String');
      if (data.hasOwnProperty('issuanceDate'))
        obj.issuanceDate = ApiClient.convertToType(data['issuanceDate'], 'Date');
      if (data.hasOwnProperty('proof'))
        obj.proof = VerifyIdentityBodySchemaInitiatorVCProof.constructFromObject(data['proof']);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
VerifiableCredentialSchema.prototype.context = undefined;

/**
 * @member {String} id
 */
VerifiableCredentialSchema.prototype.id = undefined;

/**
 * @member {Array.<String>} type
 */
VerifiableCredentialSchema.prototype.type = undefined;

/**
 * @member {module:model/VerifyIdentityBodySchemaInitiatorVCCredentialSubject} credentialSubject
 */
VerifiableCredentialSchema.prototype.credentialSubject = undefined;

/**
 * @member {String} issuer
 */
VerifiableCredentialSchema.prototype.issuer = undefined;

/**
 * @member {Date} issuanceDate
 */
VerifiableCredentialSchema.prototype.issuanceDate = undefined;

/**
 * @member {module:model/VerifyIdentityBodySchemaInitiatorVCProof} proof
 */
VerifiableCredentialSchema.prototype.proof = undefined;

