/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VerifyIdentityBodySchemaInitiatorVC} from './VerifyIdentityBodySchemaInitiatorVC';
import {VerifyIdentityBodySchemaSubject} from './VerifyIdentityBodySchemaSubject';

/**
 * The VerifyIdentityBodySchema model module.
 * @module model/VerifyIdentityBodySchema
 * @version 1.0.0
 */
export class VerifyIdentityBodySchema {
  /**
   * Constructs a new <code>VerifyIdentityBodySchema</code>.
   * @alias module:model/VerifyIdentityBodySchema
   * @class
   * @param subject {module:model/VerifyIdentityBodySchemaSubject} 
   */
  constructor(subject) {
    this.subject = subject;
  }

  /**
   * Constructs a <code>VerifyIdentityBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifyIdentityBodySchema} obj Optional instance to populate.
   * @return {module:model/VerifyIdentityBodySchema} The populated <code>VerifyIdentityBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerifyIdentityBodySchema();
      if (data.hasOwnProperty('subject'))
        obj.subject = VerifyIdentityBodySchemaSubject.constructFromObject(data['subject']);
      if (data.hasOwnProperty('initiatorVC'))
        obj.initiatorVC = VerifyIdentityBodySchemaInitiatorVC.constructFromObject(data['initiatorVC']);
    }
    return obj;
  }
}

/**
 * @member {module:model/VerifyIdentityBodySchemaSubject} subject
 */
VerifyIdentityBodySchema.prototype.subject = undefined;

/**
 * @member {module:model/VerifyIdentityBodySchemaInitiatorVC} initiatorVC
 */
VerifyIdentityBodySchema.prototype.initiatorVC = undefined;

