/*
 * Integration Services API Documentation
 * This is the API documentation for the Integration Services. Have a look at the repository for examples at [Github](https://github.com/iotaledger/integration-services).             For further information on the Audit Trail GW API have a look at [Audit Trail API](https://github.com/iotaledger/integration-services/blob/master/api/usage-audit-trail-GW.md) and head to             [SSI Bridge](https://github.com/iotaledger/integration-services/blob/master/api/usage-ssi-bridge.md) for information about the SSI Bridge.             
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The VerifiableCredentialSubjectSchema model module.
 * @module model/VerifiableCredentialSubjectSchema
 * @version 1.0.0
 */
export class VerifiableCredentialSubjectSchema {
  /**
   * Constructs a new <code>VerifiableCredentialSubjectSchema</code>.
   * @alias module:model/VerifiableCredentialSubjectSchema
   * @class
   * @param id {String} 
   * @param type {String} 
   */
  constructor(id, type) {
    this.id = id;
    this.type = type;
  }

  /**
   * Constructs a <code>VerifiableCredentialSubjectSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifiableCredentialSubjectSchema} obj Optional instance to populate.
   * @return {module:model/VerifiableCredentialSubjectSchema} The populated <code>VerifiableCredentialSubjectSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerifiableCredentialSubjectSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('initiatorId'))
        obj.initiatorId = ApiClient.convertToType(data['initiatorId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
VerifiableCredentialSubjectSchema.prototype.id = undefined;

/**
 * @member {String} type
 */
VerifiableCredentialSubjectSchema.prototype.type = undefined;

/**
 * @member {String} initiatorId
 */
VerifiableCredentialSubjectSchema.prototype.initiatorId = undefined;

