{
 "title": "RED",
 "description": "RED metric for Integration Services",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds_sum{job=\"api\", code=\"200\"}[1m])\n/\nrate(http_request_duration_microseconds_count{job=\"api\", code=\"200\"}[1m])"
    },
    {
     "expr": "rate(http_request_duration_microseconds_sum[5m]) / rate(http_request_duration_microseconds_count[5m])"
    }
   ]
  },
  {
   "title": "2XX_Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count{job=\"api\", code=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "number of requests that are failing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count{job=\"api\", code!~\"2..\"}[1m]))"
    },
    {
     "expr": "sum(increase(http_request_duration_microseconds_count{code=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_bucket{job=\"api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_microseconds_bucket[5m])) by (le)) "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_microseconds_bucket[5m])) by (le)) "
    }
   ]
  }
 ]
}